-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema exposing (allClasses, componentClasses, exclusiveGroups, parts)

{-| Generated aggregate view of the daisyUI class schema.

@docs allClasses, componentClasses, exclusiveGroups, parts

-}

import Daisy.Schema.Accordion
import Daisy.Schema.Alert
import Daisy.Schema.Aura
import Daisy.Schema.Avatar
import Daisy.Schema.Badge
import Daisy.Schema.Breadcrumbs
import Daisy.Schema.Button
import Daisy.Schema.Calendar
import Daisy.Schema.Card
import Daisy.Schema.Carousel
import Daisy.Schema.Chat
import Daisy.Schema.Checkbox
import Daisy.Schema.Collapse
import Daisy.Schema.Countdown
import Daisy.Schema.Diff
import Daisy.Schema.Divider
import Daisy.Schema.Dock
import Daisy.Schema.Drawer
import Daisy.Schema.Dropdown
import Daisy.Schema.Fab
import Daisy.Schema.Fieldset
import Daisy.Schema.FileInput
import Daisy.Schema.Filter
import Daisy.Schema.Footer
import Daisy.Schema.Hero
import Daisy.Schema.Hover3d
import Daisy.Schema.HoverGallery
import Daisy.Schema.Indicator
import Daisy.Schema.Input
import Daisy.Schema.Join
import Daisy.Schema.Kbd
import Daisy.Schema.Label
import Daisy.Schema.Link
import Daisy.Schema.List
import Daisy.Schema.Loading
import Daisy.Schema.Mask
import Daisy.Schema.Megamenu
import Daisy.Schema.Menu
import Daisy.Schema.MockupBrowser
import Daisy.Schema.MockupCode
import Daisy.Schema.MockupPhone
import Daisy.Schema.MockupWindow
import Daisy.Schema.Modal
import Daisy.Schema.Navbar
import Daisy.Schema.Otp
import Daisy.Schema.Pagination
import Daisy.Schema.Progress
import Daisy.Schema.RadialProgress
import Daisy.Schema.Radio
import Daisy.Schema.Range
import Daisy.Schema.Rating
import Daisy.Schema.Select
import Daisy.Schema.Skeleton
import Daisy.Schema.Stack
import Daisy.Schema.Stat
import Daisy.Schema.Status
import Daisy.Schema.Steps
import Daisy.Schema.Swap
import Daisy.Schema.Tab
import Daisy.Schema.Table
import Daisy.Schema.TextRotate
import Daisy.Schema.Textarea
import Daisy.Schema.ThemeController
import Daisy.Schema.Timeline
import Daisy.Schema.Toast
import Daisy.Schema.Toggle
import Daisy.Schema.Tooltip
import Daisy.Schema.Validator
import Set exposing (Set)


{-| Every daisyUI class the schema knows about.
-}
allClasses : Set String
allClasses =
    Set.fromList
        (componentClasses
            ++ List.map .part parts
            ++ List.concatMap .classes exclusiveGroups
            ++ setClasses
        )


{-| Every class in a `component` group, across all components.
-}
componentClasses : List String
componentClasses =
    List.concat
        [ Daisy.Schema.Accordion.componentClasses
        , Daisy.Schema.Alert.componentClasses
        , Daisy.Schema.Aura.componentClasses
        , Daisy.Schema.Avatar.componentClasses
        , Daisy.Schema.Badge.componentClasses
        , Daisy.Schema.Breadcrumbs.componentClasses
        , Daisy.Schema.Button.componentClasses
        , Daisy.Schema.Calendar.componentClasses
        , Daisy.Schema.Card.componentClasses
        , Daisy.Schema.Carousel.componentClasses
        , Daisy.Schema.Chat.componentClasses
        , Daisy.Schema.Checkbox.componentClasses
        , Daisy.Schema.Collapse.componentClasses
        , Daisy.Schema.Countdown.componentClasses
        , Daisy.Schema.Diff.componentClasses
        , Daisy.Schema.Divider.componentClasses
        , Daisy.Schema.Dock.componentClasses
        , Daisy.Schema.Drawer.componentClasses
        , Daisy.Schema.Dropdown.componentClasses
        , Daisy.Schema.Fab.componentClasses
        , Daisy.Schema.Fieldset.componentClasses
        , Daisy.Schema.FileInput.componentClasses
        , Daisy.Schema.Filter.componentClasses
        , Daisy.Schema.Footer.componentClasses
        , Daisy.Schema.Hero.componentClasses
        , Daisy.Schema.Hover3d.componentClasses
        , Daisy.Schema.HoverGallery.componentClasses
        , Daisy.Schema.Indicator.componentClasses
        , Daisy.Schema.Input.componentClasses
        , Daisy.Schema.Join.componentClasses
        , Daisy.Schema.Kbd.componentClasses
        , Daisy.Schema.Label.componentClasses
        , Daisy.Schema.Link.componentClasses
        , Daisy.Schema.List.componentClasses
        , Daisy.Schema.Loading.componentClasses
        , Daisy.Schema.Mask.componentClasses
        , Daisy.Schema.Megamenu.componentClasses
        , Daisy.Schema.Menu.componentClasses
        , Daisy.Schema.MockupBrowser.componentClasses
        , Daisy.Schema.MockupCode.componentClasses
        , Daisy.Schema.MockupPhone.componentClasses
        , Daisy.Schema.MockupWindow.componentClasses
        , Daisy.Schema.Modal.componentClasses
        , Daisy.Schema.Navbar.componentClasses
        , Daisy.Schema.Otp.componentClasses
        , Daisy.Schema.Pagination.componentClasses
        , Daisy.Schema.Progress.componentClasses
        , Daisy.Schema.RadialProgress.componentClasses
        , Daisy.Schema.Radio.componentClasses
        , Daisy.Schema.Range.componentClasses
        , Daisy.Schema.Rating.componentClasses
        , Daisy.Schema.Select.componentClasses
        , Daisy.Schema.Skeleton.componentClasses
        , Daisy.Schema.Stack.componentClasses
        , Daisy.Schema.Stat.componentClasses
        , Daisy.Schema.Status.componentClasses
        , Daisy.Schema.Steps.componentClasses
        , Daisy.Schema.Swap.componentClasses
        , Daisy.Schema.Tab.componentClasses
        , Daisy.Schema.Table.componentClasses
        , Daisy.Schema.TextRotate.componentClasses
        , Daisy.Schema.Textarea.componentClasses
        , Daisy.Schema.ThemeController.componentClasses
        , Daisy.Schema.Timeline.componentClasses
        , Daisy.Schema.Toast.componentClasses
        , Daisy.Schema.Toggle.componentClasses
        , Daisy.Schema.Tooltip.componentClasses
        , Daisy.Schema.Validator.componentClasses
        ]


{-| Pick-at-most-one class groups: within one entry, at most one class may
be applied to an element.
-}
exclusiveGroups : List { component : String, group : String, classes : List String }
exclusiveGroups =
    [ { component = Daisy.Schema.Alert.component
      , group = "color"
      , classes = List.map Daisy.Schema.Alert.colorToClass Daisy.Schema.Alert.allColors
      }
    , { component = Daisy.Schema.Alert.component
      , group = "style"
      , classes = List.map Daisy.Schema.Alert.styleToClass Daisy.Schema.Alert.allStyles
      }
    , { component = Daisy.Schema.Alert.component
      , group = "direction"
      , classes = List.map Daisy.Schema.Alert.directionToClass Daisy.Schema.Alert.allDirections
      }
    , { component = Daisy.Schema.Aura.component
      , group = "style"
      , classes = List.map Daisy.Schema.Aura.styleToClass Daisy.Schema.Aura.allStyles
      }
    , { component = Daisy.Schema.Aura.component
      , group = "size"
      , classes = List.map Daisy.Schema.Aura.sizeToClass Daisy.Schema.Aura.allSizes
      }
    , { component = Daisy.Schema.Badge.component
      , group = "color"
      , classes = List.map Daisy.Schema.Badge.colorToClass Daisy.Schema.Badge.allColors
      }
    , { component = Daisy.Schema.Badge.component
      , group = "style"
      , classes = List.map Daisy.Schema.Badge.styleToClass Daisy.Schema.Badge.allStyles
      }
    , { component = Daisy.Schema.Badge.component
      , group = "size"
      , classes = List.map Daisy.Schema.Badge.sizeToClass Daisy.Schema.Badge.allSizes
      }
    , { component = Daisy.Schema.Button.component
      , group = "color"
      , classes = List.map Daisy.Schema.Button.colorToClass Daisy.Schema.Button.allColors
      }
    , { component = Daisy.Schema.Button.component
      , group = "style"
      , classes = List.map Daisy.Schema.Button.styleToClass Daisy.Schema.Button.allStyles
      }
    , { component = Daisy.Schema.Button.component
      , group = "size"
      , classes = List.map Daisy.Schema.Button.sizeToClass Daisy.Schema.Button.allSizes
      }
    , { component = Daisy.Schema.Card.component
      , group = "style"
      , classes = List.map Daisy.Schema.Card.styleToClass Daisy.Schema.Card.allStyles
      }
    , { component = Daisy.Schema.Card.component
      , group = "size"
      , classes = List.map Daisy.Schema.Card.sizeToClass Daisy.Schema.Card.allSizes
      }
    , { component = Daisy.Schema.Carousel.component
      , group = "direction"
      , classes = List.map Daisy.Schema.Carousel.directionToClass Daisy.Schema.Carousel.allDirections
      }
    , { component = Daisy.Schema.Chat.component
      , group = "color"
      , classes = List.map Daisy.Schema.Chat.colorToClass Daisy.Schema.Chat.allColors
      }
    , { component = Daisy.Schema.Chat.component
      , group = "placement"
      , classes = List.map Daisy.Schema.Chat.placementToClass Daisy.Schema.Chat.allPlacements
      }
    , { component = Daisy.Schema.Checkbox.component
      , group = "color"
      , classes = List.map Daisy.Schema.Checkbox.colorToClass Daisy.Schema.Checkbox.allColors
      }
    , { component = Daisy.Schema.Checkbox.component
      , group = "size"
      , classes = List.map Daisy.Schema.Checkbox.sizeToClass Daisy.Schema.Checkbox.allSizes
      }
    , { component = Daisy.Schema.Divider.component
      , group = "color"
      , classes = List.map Daisy.Schema.Divider.colorToClass Daisy.Schema.Divider.allColors
      }
    , { component = Daisy.Schema.Divider.component
      , group = "direction"
      , classes = List.map Daisy.Schema.Divider.directionToClass Daisy.Schema.Divider.allDirections
      }
    , { component = Daisy.Schema.Divider.component
      , group = "placement"
      , classes = List.map Daisy.Schema.Divider.placementToClass Daisy.Schema.Divider.allPlacements
      }
    , { component = Daisy.Schema.Dock.component
      , group = "size"
      , classes = List.map Daisy.Schema.Dock.sizeToClass Daisy.Schema.Dock.allSizes
      }
    , { component = Daisy.Schema.Drawer.component
      , group = "placement"
      , classes = List.map Daisy.Schema.Drawer.placementToClass Daisy.Schema.Drawer.allPlacements
      }
    , { component = Daisy.Schema.Drawer.component
      , group = "variant"
      , classes = List.map Daisy.Schema.Drawer.variantToClass Daisy.Schema.Drawer.allVariants
      }
    , { component = Daisy.Schema.Dropdown.component
      , group = "placement"
      , classes = List.map Daisy.Schema.Dropdown.placementToClass Daisy.Schema.Dropdown.allPlacements
      }
    , { component = Daisy.Schema.FileInput.component
      , group = "color"
      , classes = List.map Daisy.Schema.FileInput.colorToClass Daisy.Schema.FileInput.allColors
      }
    , { component = Daisy.Schema.FileInput.component
      , group = "style"
      , classes = List.map Daisy.Schema.FileInput.styleToClass Daisy.Schema.FileInput.allStyles
      }
    , { component = Daisy.Schema.FileInput.component
      , group = "size"
      , classes = List.map Daisy.Schema.FileInput.sizeToClass Daisy.Schema.FileInput.allSizes
      }
    , { component = Daisy.Schema.Footer.component
      , group = "direction"
      , classes = List.map Daisy.Schema.Footer.directionToClass Daisy.Schema.Footer.allDirections
      }
    , { component = Daisy.Schema.Footer.component
      , group = "placement"
      , classes = List.map Daisy.Schema.Footer.placementToClass Daisy.Schema.Footer.allPlacements
      }
    , { component = Daisy.Schema.Indicator.component
      , group = "placement"
      , classes = List.map Daisy.Schema.Indicator.placementToClass Daisy.Schema.Indicator.allPlacements
      }
    , { component = Daisy.Schema.Input.component
      , group = "color"
      , classes = List.map Daisy.Schema.Input.colorToClass Daisy.Schema.Input.allColors
      }
    , { component = Daisy.Schema.Input.component
      , group = "style"
      , classes = List.map Daisy.Schema.Input.styleToClass Daisy.Schema.Input.allStyles
      }
    , { component = Daisy.Schema.Input.component
      , group = "size"
      , classes = List.map Daisy.Schema.Input.sizeToClass Daisy.Schema.Input.allSizes
      }
    , { component = Daisy.Schema.Join.component
      , group = "direction"
      , classes = List.map Daisy.Schema.Join.directionToClass Daisy.Schema.Join.allDirections
      }
    , { component = Daisy.Schema.Kbd.component
      , group = "size"
      , classes = List.map Daisy.Schema.Kbd.sizeToClass Daisy.Schema.Kbd.allSizes
      }
    , { component = Daisy.Schema.Link.component
      , group = "color"
      , classes = List.map Daisy.Schema.Link.colorToClass Daisy.Schema.Link.allColors
      }
    , { component = Daisy.Schema.Link.component
      , group = "style"
      , classes = List.map Daisy.Schema.Link.styleToClass Daisy.Schema.Link.allStyles
      }
    , { component = Daisy.Schema.Loading.component
      , group = "style"
      , classes = List.map Daisy.Schema.Loading.styleToClass Daisy.Schema.Loading.allStyles
      }
    , { component = Daisy.Schema.Loading.component
      , group = "size"
      , classes = List.map Daisy.Schema.Loading.sizeToClass Daisy.Schema.Loading.allSizes
      }
    , { component = Daisy.Schema.Mask.component
      , group = "style"
      , classes = List.map Daisy.Schema.Mask.styleToClass Daisy.Schema.Mask.allStyles
      }
    , { component = Daisy.Schema.Megamenu.component
      , group = "size"
      , classes = List.map Daisy.Schema.Megamenu.sizeToClass Daisy.Schema.Megamenu.allSizes
      }
    , { component = Daisy.Schema.Megamenu.component
      , group = "direction"
      , classes = List.map Daisy.Schema.Megamenu.directionToClass Daisy.Schema.Megamenu.allDirections
      }
    , { component = Daisy.Schema.Menu.component
      , group = "size"
      , classes = List.map Daisy.Schema.Menu.sizeToClass Daisy.Schema.Menu.allSizes
      }
    , { component = Daisy.Schema.Menu.component
      , group = "direction"
      , classes = List.map Daisy.Schema.Menu.directionToClass Daisy.Schema.Menu.allDirections
      }
    , { component = Daisy.Schema.Modal.component
      , group = "placement"
      , classes = List.map Daisy.Schema.Modal.placementToClass Daisy.Schema.Modal.allPlacements
      }
    , { component = Daisy.Schema.Otp.component
      , group = "color"
      , classes = List.map Daisy.Schema.Otp.colorToClass Daisy.Schema.Otp.allColors
      }
    , { component = Daisy.Schema.Otp.component
      , group = "size"
      , classes = List.map Daisy.Schema.Otp.sizeToClass Daisy.Schema.Otp.allSizes
      }
    , { component = Daisy.Schema.Pagination.component
      , group = "direction"
      , classes = List.map Daisy.Schema.Pagination.directionToClass Daisy.Schema.Pagination.allDirections
      }
    , { component = Daisy.Schema.Progress.component
      , group = "color"
      , classes = List.map Daisy.Schema.Progress.colorToClass Daisy.Schema.Progress.allColors
      }
    , { component = Daisy.Schema.Radio.component
      , group = "color"
      , classes = List.map Daisy.Schema.Radio.colorToClass Daisy.Schema.Radio.allColors
      }
    , { component = Daisy.Schema.Radio.component
      , group = "size"
      , classes = List.map Daisy.Schema.Radio.sizeToClass Daisy.Schema.Radio.allSizes
      }
    , { component = Daisy.Schema.Range.component
      , group = "color"
      , classes = List.map Daisy.Schema.Range.colorToClass Daisy.Schema.Range.allColors
      }
    , { component = Daisy.Schema.Range.component
      , group = "size"
      , classes = List.map Daisy.Schema.Range.sizeToClass Daisy.Schema.Range.allSizes
      }
    , { component = Daisy.Schema.Range.component
      , group = "direction"
      , classes = List.map Daisy.Schema.Range.directionToClass Daisy.Schema.Range.allDirections
      }
    , { component = Daisy.Schema.Rating.component
      , group = "size"
      , classes = List.map Daisy.Schema.Rating.sizeToClass Daisy.Schema.Rating.allSizes
      }
    , { component = Daisy.Schema.Select.component
      , group = "color"
      , classes = List.map Daisy.Schema.Select.colorToClass Daisy.Schema.Select.allColors
      }
    , { component = Daisy.Schema.Select.component
      , group = "style"
      , classes = List.map Daisy.Schema.Select.styleToClass Daisy.Schema.Select.allStyles
      }
    , { component = Daisy.Schema.Select.component
      , group = "size"
      , classes = List.map Daisy.Schema.Select.sizeToClass Daisy.Schema.Select.allSizes
      }
    , { component = Daisy.Schema.Stat.component
      , group = "direction"
      , classes = List.map Daisy.Schema.Stat.directionToClass Daisy.Schema.Stat.allDirections
      }
    , { component = Daisy.Schema.Status.component
      , group = "color"
      , classes = List.map Daisy.Schema.Status.colorToClass Daisy.Schema.Status.allColors
      }
    , { component = Daisy.Schema.Status.component
      , group = "size"
      , classes = List.map Daisy.Schema.Status.sizeToClass Daisy.Schema.Status.allSizes
      }
    , { component = Daisy.Schema.Steps.component
      , group = "color"
      , classes = List.map Daisy.Schema.Steps.colorToClass Daisy.Schema.Steps.allColors
      }
    , { component = Daisy.Schema.Steps.component
      , group = "direction"
      , classes = List.map Daisy.Schema.Steps.directionToClass Daisy.Schema.Steps.allDirections
      }
    , { component = Daisy.Schema.Swap.component
      , group = "style"
      , classes = List.map Daisy.Schema.Swap.styleToClass Daisy.Schema.Swap.allStyles
      }
    , { component = Daisy.Schema.Tab.component
      , group = "style"
      , classes = List.map Daisy.Schema.Tab.styleToClass Daisy.Schema.Tab.allStyles
      }
    , { component = Daisy.Schema.Tab.component
      , group = "size"
      , classes = List.map Daisy.Schema.Tab.sizeToClass Daisy.Schema.Tab.allSizes
      }
    , { component = Daisy.Schema.Tab.component
      , group = "placement"
      , classes = List.map Daisy.Schema.Tab.placementToClass Daisy.Schema.Tab.allPlacements
      }
    , { component = Daisy.Schema.Table.component
      , group = "size"
      , classes = List.map Daisy.Schema.Table.sizeToClass Daisy.Schema.Table.allSizes
      }
    , { component = Daisy.Schema.Textarea.component
      , group = "color"
      , classes = List.map Daisy.Schema.Textarea.colorToClass Daisy.Schema.Textarea.allColors
      }
    , { component = Daisy.Schema.Textarea.component
      , group = "style"
      , classes = List.map Daisy.Schema.Textarea.styleToClass Daisy.Schema.Textarea.allStyles
      }
    , { component = Daisy.Schema.Textarea.component
      , group = "size"
      , classes = List.map Daisy.Schema.Textarea.sizeToClass Daisy.Schema.Textarea.allSizes
      }
    , { component = Daisy.Schema.Timeline.component
      , group = "direction"
      , classes = List.map Daisy.Schema.Timeline.directionToClass Daisy.Schema.Timeline.allDirections
      }
    , { component = Daisy.Schema.Toast.component
      , group = "placement"
      , classes = List.map Daisy.Schema.Toast.placementToClass Daisy.Schema.Toast.allPlacements
      }
    , { component = Daisy.Schema.Toggle.component
      , group = "color"
      , classes = List.map Daisy.Schema.Toggle.colorToClass Daisy.Schema.Toggle.allColors
      }
    , { component = Daisy.Schema.Toggle.component
      , group = "size"
      , classes = List.map Daisy.Schema.Toggle.sizeToClass Daisy.Schema.Toggle.allSizes
      }
    , { component = Daisy.Schema.Tooltip.component
      , group = "color"
      , classes = List.map Daisy.Schema.Tooltip.colorToClass Daisy.Schema.Tooltip.allColors
      }
    , { component = Daisy.Schema.Tooltip.component
      , group = "placement"
      , classes = List.map Daisy.Schema.Tooltip.placementToClass Daisy.Schema.Tooltip.allPlacements
      }
    ]


{-| Every `part` class paired with the `component` class it must sit inside.
-}
parts : List { component : String, part : String }
parts =
    List.concat
        [ List.map (withComponent Daisy.Schema.Accordion.component) Daisy.Schema.Accordion.parts
        , List.map (withComponent Daisy.Schema.Card.component) Daisy.Schema.Card.parts
        , List.map (withComponent Daisy.Schema.Carousel.component) Daisy.Schema.Carousel.parts
        , List.map (withComponent Daisy.Schema.Chat.component) Daisy.Schema.Chat.parts
        , List.map (withComponent Daisy.Schema.Collapse.component) Daisy.Schema.Collapse.parts
        , List.map (withComponent Daisy.Schema.Diff.component) Daisy.Schema.Diff.parts
        , List.map (withComponent Daisy.Schema.Dock.component) Daisy.Schema.Dock.parts
        , List.map (withComponent Daisy.Schema.Drawer.component) Daisy.Schema.Drawer.parts
        , List.map (withComponent Daisy.Schema.Dropdown.component) Daisy.Schema.Dropdown.parts
        , List.map (withComponent Daisy.Schema.Fab.component) Daisy.Schema.Fab.parts
        , List.map (withComponent Daisy.Schema.Fieldset.component) Daisy.Schema.Fieldset.parts
        , List.map (withComponent Daisy.Schema.Filter.component) Daisy.Schema.Filter.parts
        , List.map (withComponent Daisy.Schema.Footer.component) Daisy.Schema.Footer.parts
        , List.map (withComponent Daisy.Schema.Hero.component) Daisy.Schema.Hero.parts
        , List.map (withComponent Daisy.Schema.Indicator.component) Daisy.Schema.Indicator.parts
        , List.map (withComponent Daisy.Schema.Megamenu.component) Daisy.Schema.Megamenu.parts
        , List.map (withComponent Daisy.Schema.Menu.component) Daisy.Schema.Menu.parts
        , List.map (withComponent Daisy.Schema.MockupBrowser.component) Daisy.Schema.MockupBrowser.parts
        , List.map (withComponent Daisy.Schema.MockupPhone.component) Daisy.Schema.MockupPhone.parts
        , List.map (withComponent Daisy.Schema.Modal.component) Daisy.Schema.Modal.parts
        , List.map (withComponent Daisy.Schema.Navbar.component) Daisy.Schema.Navbar.parts
        , List.map (withComponent Daisy.Schema.Pagination.component) Daisy.Schema.Pagination.parts
        , List.map (withComponent Daisy.Schema.Stat.component) Daisy.Schema.Stat.parts
        , List.map (withComponent Daisy.Schema.Steps.component) Daisy.Schema.Steps.parts
        , List.map (withComponent Daisy.Schema.Swap.component) Daisy.Schema.Swap.parts
        , List.map (withComponent Daisy.Schema.Tab.component) Daisy.Schema.Tab.parts
        , List.map (withComponent Daisy.Schema.Timeline.component) Daisy.Schema.Timeline.parts
        , List.map (withComponent Daisy.Schema.Tooltip.component) Daisy.Schema.Tooltip.parts
        , List.map (withComponent Daisy.Schema.Validator.component) Daisy.Schema.Validator.parts
        ]


withComponent : String -> String -> { component : String, part : String }
withComponent c p =
    { component = c, part = p }


setClasses : List String
setClasses =
    List.concat
        [ List.map Daisy.Schema.Accordion.modifierToClass Daisy.Schema.Accordion.allModifiers
        , List.map Daisy.Schema.Avatar.modifierToClass Daisy.Schema.Avatar.allModifiers
        , List.map Daisy.Schema.Button.modifierToClass Daisy.Schema.Button.allModifiers
        , List.map Daisy.Schema.Button.behaviorToClass Daisy.Schema.Button.allBehaviors
        , List.map Daisy.Schema.Card.modifierToClass Daisy.Schema.Card.allModifiers
        , List.map Daisy.Schema.Carousel.modifierToClass Daisy.Schema.Carousel.allModifiers
        , List.map Daisy.Schema.Collapse.modifierToClass Daisy.Schema.Collapse.allModifiers
        , List.map Daisy.Schema.Dock.modifierToClass Daisy.Schema.Dock.allModifiers
        , List.map Daisy.Schema.Drawer.modifierToClass Daisy.Schema.Drawer.allModifiers
        , List.map Daisy.Schema.Dropdown.modifierToClass Daisy.Schema.Dropdown.allModifiers
        , List.map Daisy.Schema.Fab.modifierToClass Daisy.Schema.Fab.allModifiers
        , List.map Daisy.Schema.List.modifierToClass Daisy.Schema.List.allModifiers
        , List.map Daisy.Schema.Mask.modifierToClass Daisy.Schema.Mask.allModifiers
        , List.map Daisy.Schema.Megamenu.modifierToClass Daisy.Schema.Megamenu.allModifiers
        , List.map Daisy.Schema.Menu.modifierToClass Daisy.Schema.Menu.allModifiers
        , List.map Daisy.Schema.Modal.modifierToClass Daisy.Schema.Modal.allModifiers
        , List.map Daisy.Schema.Otp.modifierToClass Daisy.Schema.Otp.allModifiers
        , List.map Daisy.Schema.Rating.modifierToClass Daisy.Schema.Rating.allModifiers
        , List.map Daisy.Schema.Skeleton.modifierToClass Daisy.Schema.Skeleton.allModifiers
        , List.map Daisy.Schema.Stack.modifierToClass Daisy.Schema.Stack.allModifiers
        , List.map Daisy.Schema.Swap.modifierToClass Daisy.Schema.Swap.allModifiers
        , List.map Daisy.Schema.Tab.modifierToClass Daisy.Schema.Tab.allModifiers
        , List.map Daisy.Schema.Table.modifierToClass Daisy.Schema.Table.allModifiers
        , List.map Daisy.Schema.Timeline.modifierToClass Daisy.Schema.Timeline.allModifiers
        , List.map Daisy.Schema.Tooltip.modifierToClass Daisy.Schema.Tooltip.allModifiers
        ]
