module Daisy.Themes exposing
    ( builtinToCustom, all
    , light, dark, cupcake, bumblebee, emerald, corporate, synthwave, retro, cyberpunk, valentine, halloween, garden, forest, aqua, lofi, pastel, fantasy, wireframe, black, luxury, dracula, cmyk, autumn, business, acid, lemonade, night, coffee, winter, dim, nord, sunset, caramellatte, abyss, silk
    )

{-| Every daisyUI built-in theme as an editable [`CustomTheme`](Daisy-Tree#CustomTheme).

**Generated by `bun tools/gen-themes.js` from
`vendor/daisyui/packages/daisyui/src/themes/*.css`. Never hand-edit.**

A [`Daisy.Tree.Theme`](Daisy-Tree#Theme) constructor is a _name_: it selects a
stylesheet rule daisyUI already ships, and there is nothing in it to read. A
theme editor needs the other thing — the 20 colours and nine
measurements behind that name — so that "start from `nord` and change the
primary" is one record update rather than twenty-nine values retyped by hand.

That is what this module is: the same declarations, as values.

    import Daisy.Themes as Themes
    import Daisy.Tree as Tree

    mine : Maybe Tree.CustomTheme
    mine =
        Tree.themeName "acme"
            |> Maybe.map (\name -> { Themes.nord | name = name })

Each value's `name` is the built-in's own reserved name
([`Daisy.Tree.themeNameOf`](Daisy-Tree#themeNameOf)), so rendering one
unchanged as `Custom nord` produces `data-theme="nord"` and the very same
colours daisyUI's own `nord` rule paints — inline instead of from the
stylesheet. Give it a name of your own
([`Daisy.Tree.themeName`](Daisy-Tree#themeName)) to make it a theme daisyUI
does not have.


# Lookup

@docs builtinToCustom, all


# The 35 themes

@docs light, dark, cupcake, bumblebee, emerald, corporate, synthwave, retro, cyberpunk, valentine, halloween, garden, forest, aqua, lofi, pastel, fantasy, wireframe, black, luxury, dracula, cmyk, autumn, business, acid, lemonade, night, coffee, winter, dim, nord, sunset, caramellatte, abyss, silk

-}

import Daisy.Tree exposing (Border(..), ColorScheme(..), CustomTheme, Radius(..), Size(..), Theme(..), themeNameOf)


{-| The values behind a built-in theme's name.

`Nothing` for a [`Theme.Custom`](Daisy-Tree#Theme) — a custom theme _is_ its
own `CustomTheme` already, and this function's job is the lookup a built-in
needs. Pattern-match if you want "the `CustomTheme` of any theme at all":

    editable : Theme -> Maybe CustomTheme
    editable theme =
        case theme of
            Custom custom ->
                Just custom

            builtin ->
                builtinToCustom builtin

-}
builtinToCustom : Theme -> Maybe CustomTheme
builtinToCustom theme =
    case theme of
        Light ->
            Just light

        Dark ->
            Just dark

        Cupcake ->
            Just cupcake

        Bumblebee ->
            Just bumblebee

        Emerald ->
            Just emerald

        Corporate ->
            Just corporate

        Synthwave ->
            Just synthwave

        Retro ->
            Just retro

        Cyberpunk ->
            Just cyberpunk

        Valentine ->
            Just valentine

        Halloween ->
            Just halloween

        Garden ->
            Just garden

        Forest ->
            Just forest

        Aqua ->
            Just aqua

        Lofi ->
            Just lofi

        Pastel ->
            Just pastel

        Fantasy ->
            Just fantasy

        Wireframe ->
            Just wireframe

        Black ->
            Just black

        Luxury ->
            Just luxury

        Dracula ->
            Just dracula

        Cmyk ->
            Just cmyk

        Autumn ->
            Just autumn

        Business ->
            Just business

        Acid ->
            Just acid

        Lemonade ->
            Just lemonade

        Night ->
            Just night

        Coffee ->
            Just coffee

        Winter ->
            Just winter

        Dim ->
            Just dim

        Nord ->
            Just nord

        Sunset ->
            Just sunset

        Caramellatte ->
            Just caramellatte

        Abyss ->
            Just abyss

        Silk ->
            Just silk

        Custom _ ->
            Nothing


{-| All 35 built-in themes, in `Daisy.Tree.allThemes` order.
-}
all : List CustomTheme
all =
    [ light
    , dark
    , cupcake
    , bumblebee
    , emerald
    , corporate
    , synthwave
    , retro
    , cyberpunk
    , valentine
    , halloween
    , garden
    , forest
    , aqua
    , lofi
    , pastel
    , fantasy
    , wireframe
    , black
    , luxury
    , dracula
    , cmyk
    , autumn
    , business
    , acid
    , lemonade
    , night
    , coffee
    , winter
    , dim
    , nord
    , sunset
    , caramellatte
    , abyss
    , silk
    ]


{-| daisyUI's `light` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/light.css` declares it.
-}
light : CustomTheme
light =
    { name = themeNameOf Light
    , colorScheme = LightScheme
    , colors =
        { base100 = { l = 100, c = 0, h = 0 }
        , base200 = { l = 98, c = 0, h = 0 }
        , base300 = { l = 95, c = 0, h = 0 }
        , baseContent = { l = 21, c = 0.006, h = 285.885 }
        , primary = { l = 45, c = 0.24, h = 277.023 }
        , primaryContent = { l = 93, c = 0.034, h = 272.788 }
        , secondary = { l = 65, c = 0.241, h = 354.308 }
        , secondaryContent = { l = 94, c = 0.028, h = 342.258 }
        , accent = { l = 77, c = 0.152, h = 181.912 }
        , accentContent = { l = 38, c = 0.063, h = 188.416 }
        , neutral = { l = 14, c = 0.005, h = 285.823 }
        , neutralContent = { l = 92, c = 0.004, h = 286.32 }
        , info = { l = 74, c = 0.16, h = 232.661 }
        , infoContent = { l = 29, c = 0.066, h = 243.157 }
        , success = { l = 76, c = 0.177, h = 163.223 }
        , successContent = { l = 37, c = 0.077, h = 168.94 }
        , warning = { l = 82, c = 0.189, h = 84.429 }
        , warningContent = { l = 41, c = 0.112, h = 45.904 }
        , error = { l = 71, c = 0.194, h = 13.428 }
        , errorContent = { l = 27, c = 0.105, h = 12.094 }
        }
    , radius = { selector = RadiusSm, field = RadiusXs, box = RadiusSm }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThin
    , depth = True
    , noise = False
    }


{-| daisyUI's `dark` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/dark.css` declares it.
-}
dark : CustomTheme
dark =
    { name = themeNameOf Dark
    , colorScheme = DarkScheme
    , colors =
        { base100 = { l = 25.33, c = 0.016, h = 252.42 }
        , base200 = { l = 23.26, c = 0.014, h = 253.1 }
        , base300 = { l = 21.15, c = 0.012, h = 254.09 }
        , baseContent = { l = 97.807, c = 0.029, h = 256.847 }
        , primary = { l = 58, c = 0.233, h = 277.117 }
        , primaryContent = { l = 96, c = 0.018, h = 272.314 }
        , secondary = { l = 65, c = 0.241, h = 354.308 }
        , secondaryContent = { l = 94, c = 0.028, h = 342.258 }
        , accent = { l = 77, c = 0.152, h = 181.912 }
        , accentContent = { l = 38, c = 0.063, h = 188.416 }
        , neutral = { l = 14, c = 0.005, h = 285.823 }
        , neutralContent = { l = 92, c = 0.004, h = 286.32 }
        , info = { l = 74, c = 0.16, h = 232.661 }
        , infoContent = { l = 29, c = 0.066, h = 243.157 }
        , success = { l = 76, c = 0.177, h = 163.223 }
        , successContent = { l = 37, c = 0.077, h = 168.94 }
        , warning = { l = 82, c = 0.189, h = 84.429 }
        , warningContent = { l = 41, c = 0.112, h = 45.904 }
        , error = { l = 71, c = 0.194, h = 13.428 }
        , errorContent = { l = 27, c = 0.105, h = 12.094 }
        }
    , radius = { selector = RadiusSm, field = RadiusXs, box = RadiusSm }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThin
    , depth = True
    , noise = False
    }


{-| daisyUI's `cupcake` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/cupcake.css` declares it.
-}
cupcake : CustomTheme
cupcake =
    { name = themeNameOf Cupcake
    , colorScheme = LightScheme
    , colors =
        { base100 = { l = 97.788, c = 0.004, h = 56.375 }
        , base200 = { l = 93.982, c = 0.007, h = 61.449 }
        , base300 = { l = 91.586, c = 0.006, h = 53.44 }
        , baseContent = { l = 23.574, c = 0.066, h = 313.189 }
        , primary = { l = 85, c = 0.138, h = 181.071 }
        , primaryContent = { l = 43, c = 0.078, h = 188.216 }
        , secondary = { l = 89, c = 0.061, h = 343.231 }
        , secondaryContent = { l = 45, c = 0.187, h = 3.815 }
        , accent = { l = 90, c = 0.076, h = 70.697 }
        , accentContent = { l = 47, c = 0.157, h = 37.304 }
        , neutral = { l = 27, c = 0.006, h = 286.033 }
        , neutralContent = { l = 92, c = 0.004, h = 286.32 }
        , info = { l = 68, c = 0.169, h = 237.323 }
        , infoContent = { l = 29, c = 0.066, h = 243.157 }
        , success = { l = 69, c = 0.17, h = 162.48 }
        , successContent = { l = 26, c = 0.051, h = 172.552 }
        , warning = { l = 79, c = 0.184, h = 86.047 }
        , warningContent = { l = 28, c = 0.066, h = 53.813 }
        , error = { l = 64, c = 0.246, h = 16.439 }
        , errorContent = { l = 27, c = 0.105, h = 12.094 }
        }
    , radius = { selector = RadiusMd, field = RadiusLg, box = RadiusMd }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThick
    , depth = True
    , noise = False
    }


{-| daisyUI's `bumblebee` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/bumblebee.css` declares it.
-}
bumblebee : CustomTheme
bumblebee =
    { name = themeNameOf Bumblebee
    , colorScheme = LightScheme
    , colors =
        { base100 = { l = 100, c = 0, h = 0 }
        , base200 = { l = 97, c = 0, h = 0 }
        , base300 = { l = 92, c = 0, h = 0 }
        , baseContent = { l = 20, c = 0, h = 0 }
        , primary = { l = 85, c = 0.199, h = 91.936 }
        , primaryContent = { l = 42, c = 0.095, h = 57.708 }
        , secondary = { l = 75, c = 0.183, h = 55.934 }
        , secondaryContent = { l = 40, c = 0.123, h = 38.172 }
        , accent = { l = 0, c = 0, h = 0 }
        , accentContent = { l = 100, c = 0, h = 0 }
        , neutral = { l = 37, c = 0.01, h = 67.558 }
        , neutralContent = { l = 92, c = 0.003, h = 48.717 }
        , info = { l = 74, c = 0.16, h = 232.661 }
        , infoContent = { l = 39, c = 0.09, h = 240.876 }
        , success = { l = 76, c = 0.177, h = 163.223 }
        , successContent = { l = 37, c = 0.077, h = 168.94 }
        , warning = { l = 82, c = 0.189, h = 84.429 }
        , warningContent = { l = 41, c = 0.112, h = 45.904 }
        , error = { l = 70, c = 0.191, h = 22.216 }
        , errorContent = { l = 39, c = 0.141, h = 25.723 }
        }
    , radius = { selector = RadiusMd, field = RadiusSm, box = RadiusMd }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThin
    , depth = True
    , noise = False
    }


{-| daisyUI's `emerald` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/emerald.css` declares it.
-}
emerald : CustomTheme
emerald =
    { name = themeNameOf Emerald
    , colorScheme = LightScheme
    , colors =
        { base100 = { l = 100, c = 0, h = 0 }
        , base200 = { l = 93, c = 0, h = 0 }
        , base300 = { l = 86, c = 0, h = 0 }
        , baseContent = { l = 35.519, c = 0.032, h = 262.988 }
        , primary = { l = 76.662, c = 0.135, h = 153.45 }
        , primaryContent = { l = 33.387, c = 0.04, h = 162.24 }
        , secondary = { l = 61.302, c = 0.202, h = 261.294 }
        , secondaryContent = { l = 100, c = 0, h = 0 }
        , accent = { l = 72.772, c = 0.149, h = 33.2 }
        , accentContent = { l = 0, c = 0, h = 0 }
        , neutral = { l = 35.519, c = 0.032, h = 262.988 }
        , neutralContent = { l = 98.462, c = 0.001, h = 247.838 }
        , info = { l = 72.06, c = 0.191, h = 231.6 }
        , infoContent = { l = 0, c = 0, h = 0 }
        , success = { l = 64.8, c = 0.15, h = 160 }
        , successContent = { l = 0, c = 0, h = 0 }
        , warning = { l = 84.71, c = 0.199, h = 83.87 }
        , warningContent = { l = 0, c = 0, h = 0 }
        , error = { l = 71.76, c = 0.221, h = 22.18 }
        , errorContent = { l = 0, c = 0, h = 0 }
        }
    , radius = { selector = RadiusMd, field = RadiusSm, box = RadiusMd }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThin
    , depth = False
    , noise = False
    }


{-| daisyUI's `corporate` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/corporate.css` declares it.
-}
corporate : CustomTheme
corporate =
    { name = themeNameOf Corporate
    , colorScheme = LightScheme
    , colors =
        { base100 = { l = 100, c = 0, h = 0 }
        , base200 = { l = 93, c = 0, h = 0 }
        , base300 = { l = 86, c = 0, h = 0 }
        , baseContent = { l = 22.389, c = 0.031, h = 278.072 }
        , primary = { l = 58, c = 0.158, h = 241.966 }
        , primaryContent = { l = 100, c = 0, h = 0 }
        , secondary = { l = 55, c = 0.046, h = 257.417 }
        , secondaryContent = { l = 100, c = 0, h = 0 }
        , accent = { l = 60, c = 0.118, h = 184.704 }
        , accentContent = { l = 100, c = 0, h = 0 }
        , neutral = { l = 0, c = 0, h = 0 }
        , neutralContent = { l = 100, c = 0, h = 0 }
        , info = { l = 60, c = 0.126, h = 221.723 }
        , infoContent = { l = 100, c = 0, h = 0 }
        , success = { l = 62, c = 0.194, h = 149.214 }
        , successContent = { l = 100, c = 0, h = 0 }
        , warning = { l = 85, c = 0.199, h = 91.936 }
        , warningContent = { l = 0, c = 0, h = 0 }
        , error = { l = 70, c = 0.191, h = 22.216 }
        , errorContent = { l = 0, c = 0, h = 0 }
        }
    , radius = { selector = RadiusXs, field = RadiusXs, box = RadiusXs }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThin
    , depth = False
    , noise = False
    }


{-| daisyUI's `synthwave` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/synthwave.css` declares it.
-}
synthwave : CustomTheme
synthwave =
    { name = themeNameOf Synthwave
    , colorScheme = DarkScheme
    , colors =
        { base100 = { l = 15, c = 0.09, h = 281.288 }
        , base200 = { l = 20, c = 0.09, h = 281.288 }
        , base300 = { l = 25, c = 0.09, h = 281.288 }
        , baseContent = { l = 78, c = 0.115, h = 274.713 }
        , primary = { l = 71, c = 0.202, h = 349.761 }
        , primaryContent = { l = 28, c = 0.109, h = 3.907 }
        , secondary = { l = 82, c = 0.111, h = 230.318 }
        , secondaryContent = { l = 29, c = 0.066, h = 243.157 }
        , accent = { l = 75, c = 0.183, h = 55.934 }
        , accentContent = { l = 26, c = 0.079, h = 36.259 }
        , neutral = { l = 45, c = 0.24, h = 277.023 }
        , neutralContent = { l = 87, c = 0.065, h = 274.039 }
        , info = { l = 74, c = 0.16, h = 232.661 }
        , infoContent = { l = 29, c = 0.066, h = 243.157 }
        , success = { l = 77, c = 0.152, h = 181.912 }
        , successContent = { l = 27, c = 0.046, h = 192.524 }
        , warning = { l = 90, c = 0.182, h = 98.111 }
        , warningContent = { l = 42, c = 0.095, h = 57.708 }
        , error = { l = 73.7, c = 0.121, h = 32.639 }
        , errorContent = { l = 23.501, c = 0.096, h = 290.329 }
        }
    , radius = { selector = RadiusMd, field = RadiusSm, box = RadiusMd }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThin
    , depth = False
    , noise = False
    }


{-| daisyUI's `retro` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/retro.css` declares it.
-}
retro : CustomTheme
retro =
    { name = themeNameOf Retro
    , colorScheme = LightScheme
    , colors =
        { base100 = { l = 91.637, c = 0.034, h = 90.515 }
        , base200 = { l = 88.272, c = 0.049, h = 91.774 }
        , base300 = { l = 84.133, c = 0.065, h = 90.856 }
        , baseContent = { l = 41, c = 0.112, h = 45.904 }
        , primary = { l = 80, c = 0.114, h = 19.571 }
        , primaryContent = { l = 39, c = 0.141, h = 25.723 }
        , secondary = { l = 92, c = 0.084, h = 155.995 }
        , secondaryContent = { l = 44, c = 0.119, h = 151.328 }
        , accent = { l = 68, c = 0.162, h = 75.834 }
        , accentContent = { l = 41, c = 0.112, h = 45.904 }
        , neutral = { l = 44, c = 0.011, h = 73.639 }
        , neutralContent = { l = 86, c = 0.005, h = 56.366 }
        , info = { l = 58, c = 0.158, h = 241.966 }
        , infoContent = { l = 96, c = 0.059, h = 95.617 }
        , success = { l = 51, c = 0.096, h = 186.391 }
        , successContent = { l = 96, c = 0.059, h = 95.617 }
        , warning = { l = 64, c = 0.222, h = 41.116 }
        , warningContent = { l = 96, c = 0.059, h = 95.617 }
        , error = { l = 70, c = 0.191, h = 22.216 }
        , errorContent = { l = 40, c = 0.123, h = 38.172 }
        }
    , radius = { selector = RadiusXs, field = RadiusXs, box = RadiusSm }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThin
    , depth = False
    , noise = False
    }


{-| daisyUI's `cyberpunk` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/cyberpunk.css` declares it.
-}
cyberpunk : CustomTheme
cyberpunk =
    { name = themeNameOf Cyberpunk
    , colorScheme = LightScheme
    , colors =
        { base100 = { l = 94.51, c = 0.179, h = 104.32 }
        , base200 = { l = 91.51, c = 0.179, h = 104.32 }
        , base300 = { l = 85.51, c = 0.179, h = 104.32 }
        , baseContent = { l = 0, c = 0, h = 0 }
        , primary = { l = 74.22, c = 0.209, h = 6.35 }
        , primaryContent = { l = 14.844, c = 0.041, h = 6.35 }
        , secondary = { l = 83.33, c = 0.184, h = 204.72 }
        , secondaryContent = { l = 16.666, c = 0.036, h = 204.72 }
        , accent = { l = 71.86, c = 0.217, h = 310.43 }
        , accentContent = { l = 14.372, c = 0.043, h = 310.43 }
        , neutral = { l = 23.04, c = 0.065, h = 269.31 }
        , neutralContent = { l = 94.51, c = 0.179, h = 104.32 }
        , info = { l = 72.06, c = 0.191, h = 231.6 }
        , infoContent = { l = 0, c = 0, h = 0 }
        , success = { l = 64.8, c = 0.15, h = 160 }
        , successContent = { l = 0, c = 0, h = 0 }
        , warning = { l = 84.71, c = 0.199, h = 83.87 }
        , warningContent = { l = 0, c = 0, h = 0 }
        , error = { l = 71.76, c = 0.221, h = 22.18 }
        , errorContent = { l = 0, c = 0, h = 0 }
        }
    , radius = { selector = RadiusNone, field = RadiusNone, box = RadiusNone }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThin
    , depth = False
    , noise = False
    }


{-| daisyUI's `valentine` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/valentine.css` declares it.
-}
valentine : CustomTheme
valentine =
    { name = themeNameOf Valentine
    , colorScheme = LightScheme
    , colors =
        { base100 = { l = 97, c = 0.014, h = 343.198 }
        , base200 = { l = 94, c = 0.028, h = 342.258 }
        , base300 = { l = 89, c = 0.061, h = 343.231 }
        , baseContent = { l = 52, c = 0.223, h = 3.958 }
        , primary = { l = 65, c = 0.241, h = 354.308 }
        , primaryContent = { l = 100, c = 0, h = 0 }
        , secondary = { l = 62, c = 0.265, h = 303.9 }
        , secondaryContent = { l = 97, c = 0.014, h = 308.299 }
        , accent = { l = 82, c = 0.111, h = 230.318 }
        , accentContent = { l = 39, c = 0.09, h = 240.876 }
        , neutral = { l = 40, c = 0.153, h = 2.432 }
        , neutralContent = { l = 89, c = 0.061, h = 343.231 }
        , info = { l = 86, c = 0.127, h = 207.078 }
        , infoContent = { l = 44, c = 0.11, h = 240.79 }
        , success = { l = 84, c = 0.143, h = 164.978 }
        , successContent = { l = 43, c = 0.095, h = 166.913 }
        , warning = { l = 75, c = 0.183, h = 55.934 }
        , warningContent = { l = 26, c = 0.079, h = 36.259 }
        , error = { l = 63, c = 0.237, h = 25.331 }
        , errorContent = { l = 97, c = 0.013, h = 17.38 }
        }
    , radius = { selector = RadiusMd, field = RadiusLg, box = RadiusMd }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThin
    , depth = False
    , noise = False
    }


{-| daisyUI's `halloween` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/halloween.css` declares it.
-}
halloween : CustomTheme
halloween =
    { name = themeNameOf Halloween
    , colorScheme = DarkScheme
    , colors =
        { base100 = { l = 21, c = 0.006, h = 56.043 }
        , base200 = { l = 14, c = 0.004, h = 49.25 }
        , base300 = { l = 0, c = 0, h = 0 }
        , baseContent = { l = 84.955, c = 0, h = 0 }
        , primary = { l = 77.48, c = 0.204, h = 60.62 }
        , primaryContent = { l = 19.693, c = 0.004, h = 196.779 }
        , secondary = { l = 45.98, c = 0.248, h = 305.03 }
        , secondaryContent = { l = 89.196, c = 0.049, h = 305.03 }
        , accent = { l = 64.8, c = 0.223, h = 136.073 }
        , accentContent = { l = 0, c = 0, h = 0 }
        , neutral = { l = 24.371, c = 0.046, h = 65.681 }
        , neutralContent = { l = 84.874, c = 0.009, h = 65.681 }
        , info = { l = 54.615, c = 0.215, h = 262.88 }
        , infoContent = { l = 90.923, c = 0.043, h = 262.88 }
        , success = { l = 62.705, c = 0.169, h = 149.213 }
        , successContent = { l = 12.541, c = 0.033, h = 149.213 }
        , warning = { l = 66.584, c = 0.157, h = 58.318 }
        , warningContent = { l = 13.316, c = 0.031, h = 58.318 }
        , error = { l = 65.72, c = 0.199, h = 27.33 }
        , errorContent = { l = 13.144, c = 0.039, h = 27.33 }
        }
    , radius = { selector = RadiusMd, field = RadiusSm, box = RadiusMd }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThin
    , depth = True
    , noise = False
    }


{-| daisyUI's `garden` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/garden.css` declares it.
-}
garden : CustomTheme
garden =
    { name = themeNameOf Garden
    , colorScheme = LightScheme
    , colors =
        { base100 = { l = 92.951, c = 0.002, h = 17.197 }
        , base200 = { l = 86.445, c = 0.002, h = 17.197 }
        , base300 = { l = 79.938, c = 0.001, h = 17.197 }
        , baseContent = { l = 16.961, c = 0.001, h = 17.32 }
        , primary = { l = 62.45, c = 0.278, h = 3.836 }
        , primaryContent = { l = 100, c = 0, h = 0 }
        , secondary = { l = 48.495, c = 0.11, h = 355.095 }
        , secondaryContent = { l = 89.699, c = 0.022, h = 355.095 }
        , accent = { l = 56.273, c = 0.054, h = 154.39 }
        , accentContent = { l = 100, c = 0, h = 0 }
        , neutral = { l = 24.155, c = 0.049, h = 89.07 }
        , neutralContent = { l = 92.951, c = 0.002, h = 17.197 }
        , info = { l = 72.06, c = 0.191, h = 231.6 }
        , infoContent = { l = 0, c = 0, h = 0 }
        , success = { l = 64.8, c = 0.15, h = 160 }
        , successContent = { l = 0, c = 0, h = 0 }
        , warning = { l = 84.71, c = 0.199, h = 83.87 }
        , warningContent = { l = 0, c = 0, h = 0 }
        , error = { l = 71.76, c = 0.221, h = 22.18 }
        , errorContent = { l = 0, c = 0, h = 0 }
        }
    , radius = { selector = RadiusMd, field = RadiusSm, box = RadiusMd }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThin
    , depth = False
    , noise = False
    }


{-| daisyUI's `forest` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/forest.css` declares it.
-}
forest : CustomTheme
forest =
    { name = themeNameOf Forest
    , colorScheme = DarkScheme
    , colors =
        { base100 = { l = 20.84, c = 0.008, h = 17.911 }
        , base200 = { l = 18.522, c = 0.007, h = 17.911 }
        , base300 = { l = 16.203, c = 0.007, h = 17.911 }
        , baseContent = { l = 83.768, c = 0.001, h = 17.911 }
        , primary = { l = 68.628, c = 0.185, h = 148.958 }
        , primaryContent = { l = 0, c = 0, h = 0 }
        , secondary = { l = 69.776, c = 0.135, h = 168.327 }
        , secondaryContent = { l = 13.955, c = 0.027, h = 168.327 }
        , accent = { l = 70.628, c = 0.119, h = 185.713 }
        , accentContent = { l = 14.125, c = 0.023, h = 185.713 }
        , neutral = { l = 30.698, c = 0.039, h = 171.364 }
        , neutralContent = { l = 86.139, c = 0.007, h = 171.364 }
        , info = { l = 72.06, c = 0.191, h = 231.6 }
        , infoContent = { l = 0, c = 0, h = 0 }
        , success = { l = 64.8, c = 0.15, h = 160 }
        , successContent = { l = 0, c = 0, h = 0 }
        , warning = { l = 84.71, c = 0.199, h = 83.87 }
        , warningContent = { l = 0, c = 0, h = 0 }
        , error = { l = 71.76, c = 0.221, h = 22.18 }
        , errorContent = { l = 0, c = 0, h = 0 }
        }
    , radius = { selector = RadiusMd, field = RadiusLg, box = RadiusMd }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThin
    , depth = False
    , noise = False
    }


{-| daisyUI's `aqua` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/aqua.css` declares it.
-}
aqua : CustomTheme
aqua =
    { name = themeNameOf Aqua
    , colorScheme = DarkScheme
    , colors =
        { base100 = { l = 37, c = 0.146, h = 265.522 }
        , base200 = { l = 28, c = 0.091, h = 267.935 }
        , base300 = { l = 22, c = 0.091, h = 267.935 }
        , baseContent = { l = 90, c = 0.058, h = 230.902 }
        , primary = { l = 85.661, c = 0.144, h = 198.645 }
        , primaryContent = { l = 40.124, c = 0.068, h = 197.603 }
        , secondary = { l = 60.682, c = 0.108, h = 309.782 }
        , secondaryContent = { l = 96, c = 0.016, h = 293.756 }
        , accent = { l = 93.426, c = 0.102, h = 94.555 }
        , accentContent = { l = 18.685, c = 0.02, h = 94.555 }
        , neutral = { l = 27, c = 0.146, h = 265.522 }
        , neutralContent = { l = 80, c = 0.146, h = 265.522 }
        , info = { l = 54.615, c = 0.215, h = 262.88 }
        , infoContent = { l = 90.923, c = 0.043, h = 262.88 }
        , success = { l = 62.705, c = 0.169, h = 149.213 }
        , successContent = { l = 12.541, c = 0.033, h = 149.213 }
        , warning = { l = 66.584, c = 0.157, h = 58.318 }
        , warningContent = { l = 27, c = 0.077, h = 45.635 }
        , error = { l = 73.95, c = 0.19, h = 27.33 }
        , errorContent = { l = 14.79, c = 0.038, h = 27.33 }
        }
    , radius = { selector = RadiusMd, field = RadiusSm, box = RadiusMd }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThin
    , depth = True
    , noise = False
    }


{-| daisyUI's `lofi` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/lofi.css` declares it.
-}
lofi : CustomTheme
lofi =
    { name = themeNameOf Lofi
    , colorScheme = LightScheme
    , colors =
        { base100 = { l = 100, c = 0, h = 0 }
        , base200 = { l = 97, c = 0, h = 0 }
        , base300 = { l = 94, c = 0, h = 0 }
        , baseContent = { l = 0, c = 0, h = 0 }
        , primary = { l = 15.906, c = 0, h = 0 }
        , primaryContent = { l = 100, c = 0, h = 0 }
        , secondary = { l = 21.455, c = 0.001, h = 17.278 }
        , secondaryContent = { l = 100, c = 0, h = 0 }
        , accent = { l = 26.861, c = 0, h = 0 }
        , accentContent = { l = 100, c = 0, h = 0 }
        , neutral = { l = 0, c = 0, h = 0 }
        , neutralContent = { l = 100, c = 0, h = 0 }
        , info = { l = 79.54, c = 0.103, h = 205.9 }
        , infoContent = { l = 15.908, c = 0.02, h = 205.9 }
        , success = { l = 90.13, c = 0.153, h = 164.14 }
        , successContent = { l = 18.026, c = 0.03, h = 164.14 }
        , warning = { l = 88.37, c = 0.135, h = 79.94 }
        , warningContent = { l = 17.674, c = 0.027, h = 79.94 }
        , error = { l = 78.66, c = 0.15, h = 28.47 }
        , errorContent = { l = 15.732, c = 0.03, h = 28.47 }
        }
    , radius = { selector = RadiusLg, field = RadiusXs, box = RadiusSm }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThin
    , depth = False
    , noise = False
    }


{-| daisyUI's `pastel` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/pastel.css` declares it.
-}
pastel : CustomTheme
pastel =
    { name = themeNameOf Pastel
    , colorScheme = LightScheme
    , colors =
        { base100 = { l = 100, c = 0, h = 0 }
        , base200 = { l = 98.462, c = 0.001, h = 247.838 }
        , base300 = { l = 92.462, c = 0.001, h = 247.838 }
        , baseContent = { l = 20, c = 0, h = 0 }
        , primary = { l = 90, c = 0.063, h = 306.703 }
        , primaryContent = { l = 49, c = 0.265, h = 301.924 }
        , secondary = { l = 89, c = 0.058, h = 10.001 }
        , secondaryContent = { l = 51, c = 0.222, h = 16.935 }
        , accent = { l = 90, c = 0.093, h = 164.15 }
        , accentContent = { l = 50, c = 0.118, h = 165.612 }
        , neutral = { l = 55, c = 0.046, h = 257.417 }
        , neutralContent = { l = 92, c = 0.013, h = 255.508 }
        , info = { l = 86, c = 0.127, h = 207.078 }
        , infoContent = { l = 52, c = 0.105, h = 223.128 }
        , success = { l = 87, c = 0.15, h = 154.449 }
        , successContent = { l = 52, c = 0.154, h = 150.069 }
        , warning = { l = 83, c = 0.128, h = 66.29 }
        , warningContent = { l = 55, c = 0.195, h = 38.402 }
        , error = { l = 80, c = 0.114, h = 19.571 }
        , errorContent = { l = 50, c = 0.213, h = 27.518 }
        }
    , radius = { selector = RadiusMd, field = RadiusLg, box = RadiusMd }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThick
    , depth = False
    , noise = False
    }


{-| daisyUI's `fantasy` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/fantasy.css` declares it.
-}
fantasy : CustomTheme
fantasy =
    { name = themeNameOf Fantasy
    , colorScheme = LightScheme
    , colors =
        { base100 = { l = 100, c = 0, h = 0 }
        , base200 = { l = 93, c = 0, h = 0 }
        , base300 = { l = 86, c = 0, h = 0 }
        , baseContent = { l = 27.807, c = 0.029, h = 256.847 }
        , primary = { l = 37.45, c = 0.189, h = 325.02 }
        , primaryContent = { l = 87.49, c = 0.037, h = 325.02 }
        , secondary = { l = 53.92, c = 0.162, h = 241.36 }
        , secondaryContent = { l = 90.784, c = 0.032, h = 241.36 }
        , accent = { l = 75.98, c = 0.204, h = 56.72 }
        , accentContent = { l = 15.196, c = 0.04, h = 56.72 }
        , neutral = { l = 27.807, c = 0.029, h = 256.847 }
        , neutralContent = { l = 85.561, c = 0.005, h = 256.847 }
        , info = { l = 72.06, c = 0.191, h = 231.6 }
        , infoContent = { l = 0, c = 0, h = 0 }
        , success = { l = 64.8, c = 0.15, h = 160 }
        , successContent = { l = 0, c = 0, h = 0 }
        , warning = { l = 84.71, c = 0.199, h = 83.87 }
        , warningContent = { l = 0, c = 0, h = 0 }
        , error = { l = 71.76, c = 0.221, h = 22.18 }
        , errorContent = { l = 0, c = 0, h = 0 }
        }
    , radius = { selector = RadiusMd, field = RadiusSm, box = RadiusMd }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThin
    , depth = True
    , noise = False
    }


{-| daisyUI's `wireframe` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/wireframe.css` declares it.
-}
wireframe : CustomTheme
wireframe =
    { name = themeNameOf Wireframe
    , colorScheme = LightScheme
    , colors =
        { base100 = { l = 100, c = 0, h = 0 }
        , base200 = { l = 97, c = 0, h = 0 }
        , base300 = { l = 94, c = 0, h = 0 }
        , baseContent = { l = 20, c = 0, h = 0 }
        , primary = { l = 87, c = 0, h = 0 }
        , primaryContent = { l = 26, c = 0, h = 0 }
        , secondary = { l = 87, c = 0, h = 0 }
        , secondaryContent = { l = 26, c = 0, h = 0 }
        , accent = { l = 87, c = 0, h = 0 }
        , accentContent = { l = 26, c = 0, h = 0 }
        , neutral = { l = 87, c = 0, h = 0 }
        , neutralContent = { l = 26, c = 0, h = 0 }
        , info = { l = 44, c = 0.11, h = 240.79 }
        , infoContent = { l = 90, c = 0.058, h = 230.902 }
        , success = { l = 43, c = 0.095, h = 166.913 }
        , successContent = { l = 90, c = 0.093, h = 164.15 }
        , warning = { l = 47, c = 0.137, h = 46.201 }
        , warningContent = { l = 92, c = 0.12, h = 95.746 }
        , error = { l = 44, c = 0.177, h = 26.899 }
        , errorContent = { l = 88, c = 0.062, h = 18.334 }
        }
    , radius = { selector = RadiusNone, field = RadiusXs, box = RadiusXs }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThin
    , depth = False
    , noise = False
    }


{-| daisyUI's `black` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/black.css` declares it.
-}
black : CustomTheme
black =
    { name = themeNameOf Black
    , colorScheme = DarkScheme
    , colors =
        { base100 = { l = 0, c = 0, h = 0 }
        , base200 = { l = 19, c = 0, h = 0 }
        , base300 = { l = 22, c = 0, h = 0 }
        , baseContent = { l = 87.609, c = 0, h = 0 }
        , primary = { l = 35, c = 0, h = 0 }
        , primaryContent = { l = 100, c = 0, h = 0 }
        , secondary = { l = 35, c = 0, h = 0 }
        , secondaryContent = { l = 100, c = 0, h = 0 }
        , accent = { l = 35, c = 0, h = 0 }
        , accentContent = { l = 100, c = 0, h = 0 }
        , neutral = { l = 35, c = 0, h = 0 }
        , neutralContent = { l = 100, c = 0, h = 0 }
        , info = { l = 45.201, c = 0.313, h = 264.052 }
        , infoContent = { l = 89.04, c = 0.062, h = 264.052 }
        , success = { l = 51.975, c = 0.176, h = 142.495 }
        , successContent = { l = 90.395, c = 0.035, h = 142.495 }
        , warning = { l = 96.798, c = 0.211, h = 109.769 }
        , warningContent = { l = 19.359, c = 0.042, h = 109.769 }
        , error = { l = 62.795, c = 0.257, h = 29.233 }
        , errorContent = { l = 12.559, c = 0.051, h = 29.233 }
        }
    , radius = { selector = RadiusNone, field = RadiusNone, box = RadiusNone }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThin
    , depth = False
    , noise = False
    }


{-| daisyUI's `luxury` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/luxury.css` declares it.
-}
luxury : CustomTheme
luxury =
    { name = themeNameOf Luxury
    , colorScheme = DarkScheme
    , colors =
        { base100 = { l = 14.076, c = 0.004, h = 285.822 }
        , base200 = { l = 20.219, c = 0.004, h = 308.229 }
        , base300 = { l = 23.219, c = 0.004, h = 308.229 }
        , baseContent = { l = 75.687, c = 0.123, h = 76.89 }
        , primary = { l = 100, c = 0, h = 0 }
        , primaryContent = { l = 20, c = 0, h = 0 }
        , secondary = { l = 27.581, c = 0.064, h = 261.069 }
        , secondaryContent = { l = 85.516, c = 0.012, h = 261.069 }
        , accent = { l = 36.674, c = 0.051, h = 338.825 }
        , accentContent = { l = 87.334, c = 0.01, h = 338.825 }
        , neutral = { l = 24.27, c = 0.057, h = 59.825 }
        , neutralContent = { l = 93.203, c = 0.089, h = 90.861 }
        , info = { l = 79.061, c = 0.121, h = 237.133 }
        , infoContent = { l = 15.812, c = 0.024, h = 237.133 }
        , success = { l = 78.119, c = 0.192, h = 132.154 }
        , successContent = { l = 15.623, c = 0.038, h = 132.154 }
        , warning = { l = 86.127, c = 0.136, h = 102.891 }
        , warningContent = { l = 17.225, c = 0.027, h = 102.891 }
        , error = { l = 71.753, c = 0.176, h = 22.568 }
        , errorContent = { l = 14.35, c = 0.035, h = 22.568 }
        }
    , radius = { selector = RadiusMd, field = RadiusSm, box = RadiusMd }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThin
    , depth = True
    , noise = False
    }


{-| daisyUI's `dracula` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/dracula.css` declares it.
-}
dracula : CustomTheme
dracula =
    { name = themeNameOf Dracula
    , colorScheme = DarkScheme
    , colors =
        { base100 = { l = 28.822, c = 0.022, h = 277.508 }
        , base200 = { l = 26.805, c = 0.02, h = 277.508 }
        , base300 = { l = 24.787, c = 0.019, h = 277.508 }
        , baseContent = { l = 97.747, c = 0.007, h = 106.545 }
        , primary = { l = 75.461, c = 0.183, h = 346.812 }
        , primaryContent = { l = 15.092, c = 0.036, h = 346.812 }
        , secondary = { l = 74.202, c = 0.148, h = 301.883 }
        , secondaryContent = { l = 14.84, c = 0.029, h = 301.883 }
        , accent = { l = 83.392, c = 0.124, h = 66.558 }
        , accentContent = { l = 16.678, c = 0.024, h = 66.558 }
        , neutral = { l = 39.445, c = 0.032, h = 275.524 }
        , neutralContent = { l = 87.889, c = 0.006, h = 275.524 }
        , info = { l = 88.263, c = 0.093, h = 212.846 }
        , infoContent = { l = 17.652, c = 0.018, h = 212.846 }
        , success = { l = 87.099, c = 0.219, h = 148.024 }
        , successContent = { l = 17.419, c = 0.043, h = 148.024 }
        , warning = { l = 95.533, c = 0.134, h = 112.757 }
        , warningContent = { l = 19.106, c = 0.026, h = 112.757 }
        , error = { l = 68.22, c = 0.206, h = 24.43 }
        , errorContent = { l = 13.644, c = 0.041, h = 24.43 }
        }
    , radius = { selector = RadiusMd, field = RadiusSm, box = RadiusMd }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThin
    , depth = False
    , noise = False
    }


{-| daisyUI's `cmyk` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/cmyk.css` declares it.
-}
cmyk : CustomTheme
cmyk =
    { name = themeNameOf Cmyk
    , colorScheme = LightScheme
    , colors =
        { base100 = { l = 100, c = 0, h = 0 }
        , base200 = { l = 95, c = 0, h = 0 }
        , base300 = { l = 90, c = 0, h = 0 }
        , baseContent = { l = 20, c = 0, h = 0 }
        , primary = { l = 71.772, c = 0.133, h = 239.443 }
        , primaryContent = { l = 14.354, c = 0.026, h = 239.443 }
        , secondary = { l = 64.476, c = 0.202, h = 359.339 }
        , secondaryContent = { l = 12.895, c = 0.04, h = 359.339 }
        , accent = { l = 94.228, c = 0.189, h = 105.306 }
        , accentContent = { l = 18.845, c = 0.037, h = 105.306 }
        , neutral = { l = 21.778, c = 0, h = 0 }
        , neutralContent = { l = 84.355, c = 0, h = 0 }
        , info = { l = 68.475, c = 0.094, h = 217.284 }
        , infoContent = { l = 13.695, c = 0.018, h = 217.284 }
        , success = { l = 46.949, c = 0.162, h = 321.406 }
        , successContent = { l = 89.389, c = 0.032, h = 321.406 }
        , warning = { l = 71.236, c = 0.159, h = 52.023 }
        , warningContent = { l = 14.247, c = 0.031, h = 52.023 }
        , error = { l = 62.013, c = 0.208, h = 28.717 }
        , errorContent = { l = 12.402, c = 0.041, h = 28.717 }
        }
    , radius = { selector = RadiusMd, field = RadiusSm, box = RadiusMd }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThin
    , depth = False
    , noise = False
    }


{-| daisyUI's `autumn` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/autumn.css` declares it.
-}
autumn : CustomTheme
autumn =
    { name = themeNameOf Autumn
    , colorScheme = LightScheme
    , colors =
        { base100 = { l = 95.814, c = 0, h = 0 }
        , base200 = { l = 89.107, c = 0, h = 0 }
        , base300 = { l = 82.4, c = 0, h = 0 }
        , baseContent = { l = 19.162, c = 0, h = 0 }
        , primary = { l = 40.723, c = 0.161, h = 17.53 }
        , primaryContent = { l = 88.144, c = 0.032, h = 17.53 }
        , secondary = { l = 61.676, c = 0.169, h = 23.865 }
        , secondaryContent = { l = 12.335, c = 0.033, h = 23.865 }
        , accent = { l = 73.425, c = 0.094, h = 60.729 }
        , accentContent = { l = 14.685, c = 0.018, h = 60.729 }
        , neutral = { l = 54.367, c = 0.037, h = 51.902 }
        , neutralContent = { l = 90.873, c = 0.007, h = 51.902 }
        , info = { l = 69.224, c = 0.097, h = 207.284 }
        , infoContent = { l = 13.844, c = 0.019, h = 207.284 }
        , success = { l = 60.995, c = 0.08, h = 174.616 }
        , successContent = { l = 12.199, c = 0.016, h = 174.616 }
        , warning = { l = 70.081, c = 0.164, h = 56.844 }
        , warningContent = { l = 14.016, c = 0.032, h = 56.844 }
        , error = { l = 53.07, c = 0.241, h = 24.16 }
        , errorContent = { l = 90.614, c = 0.048, h = 24.16 }
        }
    , radius = { selector = RadiusMd, field = RadiusSm, box = RadiusMd }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThin
    , depth = True
    , noise = False
    }


{-| daisyUI's `business` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/business.css` declares it.
-}
business : CustomTheme
business =
    { name = themeNameOf Business
    , colorScheme = DarkScheme
    , colors =
        { base100 = { l = 24.353, c = 0, h = 0 }
        , base200 = { l = 22.648, c = 0, h = 0 }
        , base300 = { l = 20.944, c = 0, h = 0 }
        , baseContent = { l = 84.87, c = 0, h = 0 }
        , primary = { l = 41.703, c = 0.099, h = 251.473 }
        , primaryContent = { l = 88.34, c = 0.019, h = 251.473 }
        , secondary = { l = 64.092, c = 0.027, h = 229.389 }
        , secondaryContent = { l = 12.818, c = 0.005, h = 229.389 }
        , accent = { l = 67.271, c = 0.167, h = 35.791 }
        , accentContent = { l = 13.454, c = 0.033, h = 35.791 }
        , neutral = { l = 27.441, c = 0.013, h = 253.041 }
        , neutralContent = { l = 85.488, c = 0.002, h = 253.041 }
        , info = { l = 62.616, c = 0.143, h = 240.033 }
        , infoContent = { l = 12.523, c = 0.028, h = 240.033 }
        , success = { l = 70.226, c = 0.094, h = 156.596 }
        , successContent = { l = 14.045, c = 0.018, h = 156.596 }
        , warning = { l = 77.482, c = 0.115, h = 81.519 }
        , warningContent = { l = 15.496, c = 0.023, h = 81.519 }
        , error = { l = 51.61, c = 0.146, h = 29.674 }
        , errorContent = { l = 90.322, c = 0.029, h = 29.674 }
        }
    , radius = { selector = RadiusNone, field = RadiusXs, box = RadiusXs }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThin
    , depth = False
    , noise = False
    }


{-| daisyUI's `acid` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/acid.css` declares it.
-}
acid : CustomTheme
acid =
    { name = themeNameOf Acid
    , colorScheme = LightScheme
    , colors =
        { base100 = { l = 98, c = 0, h = 0 }
        , base200 = { l = 95, c = 0, h = 0 }
        , base300 = { l = 91, c = 0, h = 0 }
        , baseContent = { l = 0, c = 0, h = 0 }
        , primary = { l = 71.9, c = 0.357, h = 330.759 }
        , primaryContent = { l = 14.38, c = 0.071, h = 330.759 }
        , secondary = { l = 73.37, c = 0.224, h = 48.25 }
        , secondaryContent = { l = 14.674, c = 0.044, h = 48.25 }
        , accent = { l = 92.78, c = 0.264, h = 122.962 }
        , accentContent = { l = 18.556, c = 0.052, h = 122.962 }
        , neutral = { l = 21.31, c = 0.128, h = 278.68 }
        , neutralContent = { l = 84.262, c = 0.025, h = 278.68 }
        , info = { l = 60.72, c = 0.227, h = 252.05 }
        , infoContent = { l = 12.144, c = 0.045, h = 252.05 }
        , success = { l = 85.72, c = 0.266, h = 158.53 }
        , successContent = { l = 17.144, c = 0.053, h = 158.53 }
        , warning = { l = 91.01, c = 0.212, h = 100.5 }
        , warningContent = { l = 18.202, c = 0.042, h = 100.5 }
        , error = { l = 64.84, c = 0.293, h = 29.349 }
        , errorContent = { l = 12.968, c = 0.058, h = 29.349 }
        }
    , radius = { selector = RadiusMd, field = RadiusMd, box = RadiusMd }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThin
    , depth = True
    , noise = False
    }


{-| daisyUI's `lemonade` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/lemonade.css` declares it.
-}
lemonade : CustomTheme
lemonade =
    { name = themeNameOf Lemonade
    , colorScheme = LightScheme
    , colors =
        { base100 = { l = 98.71, c = 0.02, h = 123.72 }
        , base200 = { l = 91.8, c = 0.018, h = 123.72 }
        , base300 = { l = 84.89, c = 0.017, h = 123.72 }
        , baseContent = { l = 19.742, c = 0.004, h = 123.72 }
        , primary = { l = 58.92, c = 0.199, h = 134.6 }
        , primaryContent = { l = 11.784, c = 0.039, h = 134.6 }
        , secondary = { l = 77.75, c = 0.196, h = 111.09 }
        , secondaryContent = { l = 15.55, c = 0.039, h = 111.09 }
        , accent = { l = 85.39, c = 0.201, h = 100.73 }
        , accentContent = { l = 17.078, c = 0.04, h = 100.73 }
        , neutral = { l = 30.98, c = 0.075, h = 108.6 }
        , neutralContent = { l = 86.196, c = 0.015, h = 108.6 }
        , info = { l = 86.19, c = 0.047, h = 224.14 }
        , infoContent = { l = 17.238, c = 0.009, h = 224.14 }
        , success = { l = 86.19, c = 0.047, h = 157.85 }
        , successContent = { l = 17.238, c = 0.009, h = 157.85 }
        , warning = { l = 86.19, c = 0.047, h = 102.15 }
        , warningContent = { l = 17.238, c = 0.009, h = 102.15 }
        , error = { l = 86.19, c = 0.047, h = 25.85 }
        , errorContent = { l = 17.238, c = 0.009, h = 25.85 }
        }
    , radius = { selector = RadiusMd, field = RadiusSm, box = RadiusMd }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThin
    , depth = False
    , noise = False
    }


{-| daisyUI's `night` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/night.css` declares it.
-}
night : CustomTheme
night =
    { name = themeNameOf Night
    , colorScheme = DarkScheme
    , colors =
        { base100 = { l = 20.768, c = 0.039, h = 265.754 }
        , base200 = { l = 19.314, c = 0.037, h = 265.754 }
        , base300 = { l = 17.86, c = 0.034, h = 265.754 }
        , baseContent = { l = 84.153, c = 0.007, h = 265.754 }
        , primary = { l = 75.351, c = 0.138, h = 232.661 }
        , primaryContent = { l = 15.07, c = 0.027, h = 232.661 }
        , secondary = { l = 68.011, c = 0.158, h = 276.934 }
        , secondaryContent = { l = 13.602, c = 0.031, h = 276.934 }
        , accent = { l = 72.36, c = 0.176, h = 350.048 }
        , accentContent = { l = 14.472, c = 0.035, h = 350.048 }
        , neutral = { l = 27.949, c = 0.036, h = 260.03 }
        , neutralContent = { l = 85.589, c = 0.007, h = 260.03 }
        , info = { l = 68.455, c = 0.148, h = 237.251 }
        , infoContent = { l = 0, c = 0, h = 0 }
        , success = { l = 78.452, c = 0.132, h = 181.911 }
        , successContent = { l = 15.69, c = 0.026, h = 181.911 }
        , warning = { l = 83.242, c = 0.139, h = 82.95 }
        , warningContent = { l = 16.648, c = 0.027, h = 82.95 }
        , error = { l = 71.785, c = 0.17, h = 13.118 }
        , errorContent = { l = 14.357, c = 0.034, h = 13.118 }
        }
    , radius = { selector = RadiusMd, field = RadiusSm, box = RadiusMd }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThin
    , depth = False
    , noise = False
    }


{-| daisyUI's `coffee` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/coffee.css` declares it.
-}
coffee : CustomTheme
coffee =
    { name = themeNameOf Coffee
    , colorScheme = DarkScheme
    , colors =
        { base100 = { l = 24, c = 0.023, h = 329.708 }
        , base200 = { l = 21, c = 0.021, h = 329.708 }
        , base300 = { l = 16, c = 0.019, h = 329.708 }
        , baseContent = { l = 72.354, c = 0.092, h = 79.129 }
        , primary = { l = 71.996, c = 0.123, h = 62.756 }
        , primaryContent = { l = 14.399, c = 0.024, h = 62.756 }
        , secondary = { l = 34.465, c = 0.029, h = 199.194 }
        , secondaryContent = { l = 86.893, c = 0.005, h = 199.194 }
        , accent = { l = 42.621, c = 0.074, h = 224.389 }
        , accentContent = { l = 88.524, c = 0.014, h = 224.389 }
        , neutral = { l = 16.51, c = 0.015, h = 326.261 }
        , neutralContent = { l = 83.302, c = 0.003, h = 326.261 }
        , info = { l = 79.49, c = 0.063, h = 184.558 }
        , infoContent = { l = 15.898, c = 0.012, h = 184.558 }
        , success = { l = 74.722, c = 0.072, h = 131.116 }
        , successContent = { l = 14.944, c = 0.014, h = 131.116 }
        , warning = { l = 88.15, c = 0.14, h = 87.722 }
        , warningContent = { l = 17.63, c = 0.028, h = 87.722 }
        , error = { l = 77.318, c = 0.128, h = 31.871 }
        , errorContent = { l = 15.463, c = 0.025, h = 31.871 }
        }
    , radius = { selector = RadiusMd, field = RadiusSm, box = RadiusMd }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThin
    , depth = False
    , noise = False
    }


{-| daisyUI's `winter` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/winter.css` declares it.
-}
winter : CustomTheme
winter =
    { name = themeNameOf Winter
    , colorScheme = LightScheme
    , colors =
        { base100 = { l = 100, c = 0, h = 0 }
        , base200 = { l = 97.466, c = 0.011, h = 259.822 }
        , base300 = { l = 93.268, c = 0.016, h = 262.751 }
        , baseContent = { l = 41.886, c = 0.053, h = 255.824 }
        , primary = { l = 56.86, c = 0.255, h = 257.57 }
        , primaryContent = { l = 91.372, c = 0.051, h = 257.57 }
        , secondary = { l = 42.551, c = 0.161, h = 282.339 }
        , secondaryContent = { l = 88.51, c = 0.032, h = 282.339 }
        , accent = { l = 59.939, c = 0.191, h = 335.171 }
        , accentContent = { l = 11.988, c = 0.038, h = 335.171 }
        , neutral = { l = 19.616, c = 0.063, h = 257.651 }
        , neutralContent = { l = 83.923, c = 0.012, h = 257.651 }
        , info = { l = 88.127, c = 0.085, h = 214.515 }
        , infoContent = { l = 17.625, c = 0.017, h = 214.515 }
        , success = { l = 80.494, c = 0.077, h = 197.823 }
        , successContent = { l = 16.098, c = 0.015, h = 197.823 }
        , warning = { l = 89.172, c = 0.045, h = 71.47 }
        , warningContent = { l = 17.834, c = 0.009, h = 71.47 }
        , error = { l = 73.092, c = 0.11, h = 20.076 }
        , errorContent = { l = 14.618, c = 0.022, h = 20.076 }
        }
    , radius = { selector = RadiusMd, field = RadiusSm, box = RadiusMd }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThin
    , depth = False
    , noise = False
    }


{-| daisyUI's `dim` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/dim.css` declares it.
-}
dim : CustomTheme
dim =
    { name = themeNameOf Dim
    , colorScheme = DarkScheme
    , colors =
        { base100 = { l = 30.857, c = 0.023, h = 264.149 }
        , base200 = { l = 28.036, c = 0.019, h = 264.182 }
        , base300 = { l = 26.346, c = 0.018, h = 262.177 }
        , baseContent = { l = 82.901, c = 0.031, h = 222.959 }
        , primary = { l = 86.133, c = 0.141, h = 139.549 }
        , primaryContent = { l = 17.226, c = 0.028, h = 139.549 }
        , secondary = { l = 73.375, c = 0.165, h = 35.353 }
        , secondaryContent = { l = 14.675, c = 0.033, h = 35.353 }
        , accent = { l = 74.229, c = 0.133, h = 311.379 }
        , accentContent = { l = 14.845, c = 0.026, h = 311.379 }
        , neutral = { l = 24.731, c = 0.02, h = 264.094 }
        , neutralContent = { l = 82.901, c = 0.031, h = 222.959 }
        , info = { l = 86.078, c = 0.142, h = 206.182 }
        , infoContent = { l = 17.215, c = 0.028, h = 206.182 }
        , success = { l = 86.171, c = 0.142, h = 166.534 }
        , successContent = { l = 17.234, c = 0.028, h = 166.534 }
        , warning = { l = 86.163, c = 0.142, h = 94.818 }
        , warningContent = { l = 17.232, c = 0.028, h = 94.818 }
        , error = { l = 82.418, c = 0.099, h = 33.756 }
        , errorContent = { l = 16.483, c = 0.019, h = 33.756 }
        }
    , radius = { selector = RadiusMd, field = RadiusSm, box = RadiusMd }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThin
    , depth = False
    , noise = False
    }


{-| daisyUI's `nord` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/nord.css` declares it.
-}
nord : CustomTheme
nord =
    { name = themeNameOf Nord
    , colorScheme = LightScheme
    , colors =
        { base100 = { l = 95.127, c = 0.007, h = 260.731 }
        , base200 = { l = 93.299, c = 0.01, h = 261.788 }
        , base300 = { l = 89.925, c = 0.016, h = 262.749 }
        , baseContent = { l = 32.437, c = 0.022, h = 264.182 }
        , primary = { l = 59.435, c = 0.077, h = 254.027 }
        , primaryContent = { l = 11.887, c = 0.015, h = 254.027 }
        , secondary = { l = 69.651, c = 0.059, h = 248.687 }
        , secondaryContent = { l = 13.93, c = 0.011, h = 248.687 }
        , accent = { l = 77.464, c = 0.062, h = 217.469 }
        , accentContent = { l = 15.492, c = 0.012, h = 217.469 }
        , neutral = { l = 45.229, c = 0.035, h = 264.131 }
        , neutralContent = { l = 89.925, c = 0.016, h = 262.749 }
        , info = { l = 69.207, c = 0.062, h = 332.664 }
        , infoContent = { l = 13.841, c = 0.012, h = 332.664 }
        , success = { l = 76.827, c = 0.074, h = 131.063 }
        , successContent = { l = 15.365, c = 0.014, h = 131.063 }
        , warning = { l = 85.486, c = 0.089, h = 84.093 }
        , warningContent = { l = 17.097, c = 0.017, h = 84.093 }
        , error = { l = 60.61, c = 0.12, h = 15.341 }
        , errorContent = { l = 12.122, c = 0.024, h = 15.341 }
        }
    , radius = { selector = RadiusMd, field = RadiusXs, box = RadiusSm }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThin
    , depth = False
    , noise = False
    }


{-| daisyUI's `sunset` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/sunset.css` declares it.
-}
sunset : CustomTheme
sunset =
    { name = themeNameOf Sunset
    , colorScheme = DarkScheme
    , colors =
        { base100 = { l = 22, c = 0.019, h = 237.69 }
        , base200 = { l = 20, c = 0.019, h = 237.69 }
        , base300 = { l = 18, c = 0.019, h = 237.69 }
        , baseContent = { l = 77.383, c = 0.043, h = 245.096 }
        , primary = { l = 74.703, c = 0.158, h = 39.947 }
        , primaryContent = { l = 14.94, c = 0.031, h = 39.947 }
        , secondary = { l = 72.537, c = 0.177, h = 2.72 }
        , secondaryContent = { l = 14.507, c = 0.035, h = 2.72 }
        , accent = { l = 71.294, c = 0.166, h = 299.844 }
        , accentContent = { l = 14.258, c = 0.033, h = 299.844 }
        , neutral = { l = 26, c = 0.019, h = 237.69 }
        , neutralContent = { l = 70, c = 0.019, h = 237.69 }
        , info = { l = 85.559, c = 0.085, h = 206.015 }
        , infoContent = { l = 17.111, c = 0.017, h = 206.015 }
        , success = { l = 85.56, c = 0.085, h = 144.778 }
        , successContent = { l = 17.112, c = 0.017, h = 144.778 }
        , warning = { l = 85.569, c = 0.084, h = 74.427 }
        , warningContent = { l = 17.113, c = 0.016, h = 74.427 }
        , error = { l = 85.511, c = 0.078, h = 16.886 }
        , errorContent = { l = 17.102, c = 0.015, h = 16.886 }
        }
    , radius = { selector = RadiusMd, field = RadiusSm, box = RadiusMd }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThin
    , depth = False
    , noise = False
    }


{-| daisyUI's `caramellatte` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/caramellatte.css` declares it.
-}
caramellatte : CustomTheme
caramellatte =
    { name = themeNameOf Caramellatte
    , colorScheme = LightScheme
    , colors =
        { base100 = { l = 98, c = 0.016, h = 73.684 }
        , base200 = { l = 95, c = 0.038, h = 75.164 }
        , base300 = { l = 90, c = 0.076, h = 70.697 }
        , baseContent = { l = 40, c = 0.123, h = 38.172 }
        , primary = { l = 0, c = 0, h = 0 }
        , primaryContent = { l = 100, c = 0, h = 0 }
        , secondary = { l = 22.45, c = 0.075, h = 37.85 }
        , secondaryContent = { l = 90, c = 0.076, h = 70.697 }
        , accent = { l = 46.44, c = 0.111, h = 37.85 }
        , accentContent = { l = 90, c = 0.076, h = 70.697 }
        , neutral = { l = 55, c = 0.195, h = 38.402 }
        , neutralContent = { l = 98, c = 0.016, h = 73.684 }
        , info = { l = 42, c = 0.199, h = 265.638 }
        , infoContent = { l = 90, c = 0.076, h = 70.697 }
        , success = { l = 43, c = 0.095, h = 166.913 }
        , successContent = { l = 90, c = 0.076, h = 70.697 }
        , warning = { l = 82, c = 0.189, h = 84.429 }
        , warningContent = { l = 41, c = 0.112, h = 45.904 }
        , error = { l = 70, c = 0.191, h = 22.216 }
        , errorContent = { l = 39, c = 0.141, h = 25.723 }
        }
    , radius = { selector = RadiusLg, field = RadiusSm, box = RadiusMd }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThick
    , depth = True
    , noise = True
    }


{-| daisyUI's `abyss` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/abyss.css` declares it.
-}
abyss : CustomTheme
abyss =
    { name = themeNameOf Abyss
    , colorScheme = DarkScheme
    , colors =
        { base100 = { l = 20, c = 0.08, h = 209 }
        , base200 = { l = 15, c = 0.08, h = 209 }
        , base300 = { l = 10, c = 0.08, h = 209 }
        , baseContent = { l = 90, c = 0.076, h = 70.697 }
        , primary = { l = 92, c = 0.2653, h = 125 }
        , primaryContent = { l = 50, c = 0.2653, h = 125 }
        , secondary = { l = 83.27, c = 0.0764, h = 298.3 }
        , secondaryContent = { l = 43.27, c = 0.0764, h = 298.3 }
        , accent = { l = 43, c = 0, h = 0 }
        , accentContent = { l = 98, c = 0, h = 0 }
        , neutral = { l = 30, c = 0.08, h = 209 }
        , neutralContent = { l = 90, c = 0.076, h = 70.697 }
        , info = { l = 74, c = 0.16, h = 232.661 }
        , infoContent = { l = 29, c = 0.066, h = 243.157 }
        , success = { l = 79, c = 0.209, h = 151.711 }
        , successContent = { l = 26, c = 0.065, h = 152.934 }
        , warning = { l = 84.8, c = 0.1962, h = 84.62 }
        , warningContent = { l = 44.8, c = 0.1962, h = 84.62 }
        , error = { l = 65, c = 0.1985, h = 24.22 }
        , errorContent = { l = 27, c = 0.1985, h = 24.22 }
        }
    , radius = { selector = RadiusLg, field = RadiusXs, box = RadiusSm }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThin
    , depth = True
    , noise = False
    }


{-| daisyUI's `silk` theme, exactly as
`vendor/daisyui/packages/daisyui/src/themes/silk.css` declares it.
-}
silk : CustomTheme
silk =
    { name = themeNameOf Silk
    , colorScheme = LightScheme
    , colors =
        { base100 = { l = 97, c = 0.0035, h = 67.78 }
        , base200 = { l = 95, c = 0.0081, h = 61.42 }
        , base300 = { l = 90, c = 0.0081, h = 61.42 }
        , baseContent = { l = 40, c = 0.0081, h = 61.42 }
        , primary = { l = 23.27, c = 0.0249, h = 284.3 }
        , primaryContent = { l = 94.22, c = 0.2505, h = 117.44 }
        , secondary = { l = 23.27, c = 0.0249, h = 284.3 }
        , secondaryContent = { l = 73.92, c = 0.2135, h = 50.94 }
        , accent = { l = 23.27, c = 0.0249, h = 284.3 }
        , accentContent = { l = 88.92, c = 0.2061, h = 189.9 }
        , neutral = { l = 20, c = 0, h = 0 }
        , neutralContent = { l = 80, c = 0.0081, h = 61.42 }
        , info = { l = 80.39, c = 0.1148, h = 241.68 }
        , infoContent = { l = 30.39, c = 0.1148, h = 241.68 }
        , success = { l = 83.92, c = 0.0901, h = 136.87 }
        , successContent = { l = 23.92, c = 0.0901, h = 136.87 }
        , warning = { l = 83.92, c = 0.1085, h = 80 }
        , warningContent = { l = 43.92, c = 0.1085, h = 80 }
        , error = { l = 75.1, c = 0.1814, h = 22.37 }
        , errorContent = { l = 35.1, c = 0.1814, h = 22.37 }
        }
    , radius = { selector = RadiusLg, field = RadiusSm, box = RadiusMd }
    , size = { selector = SizeMd, field = SizeMd }
    , border = BorderThick
    , depth = True
    , noise = False
    }
