module NoRawSchemaStrings exposing (rule)

{-| Forbids string literals that exactly equal a daisyUI class from
`fixtures/schema.json`, everywhere except `Daisy.Schema`, `Daisy.Schema.*`
(the generated schema modules, which legitimately hold these strings), and
`Daisy.Render` (the one module allowed to emit class strings; see
NoClassOutsideRender). Everywhere else, a raw string that happens to spell a
schema class is a sign someone is bypassing `Daisy.Tree`/`Daisy.Schema` and
hand-writing a class name instead of using a generated constructor.

The class list is baked into `SchemaClasses.elm` (generated by
`tools/gen-review-classes.js` from `fixtures/schema.json`) because rules
cannot read files at runtime -- see CLAUDE.md "Commands"
(`bun tools/gen-review-classes.js`) and ReviewConfig.elm for the
`tests/`-directory carve-out (test fixtures legitimately assert against
literal class strings, e.g. `"card-body"` in PartsTest; that's handled with
`Rule.ignoreErrorsForDirectories [ "tests/" ]` when this rule is registered,
not inside this module).

-}

import Elm.Syntax.Expression as Expression exposing (Expression)
import Elm.Syntax.Node as Node exposing (Node)
import Review.Rule as Rule exposing (Rule)
import SchemaClasses
import Set


type alias Context =
    { isExemptModule : Bool
    }


rule : Rule
rule =
    Rule.newModuleRuleSchemaUsingContextCreator "NoRawSchemaStrings" contextCreator
        |> Rule.withExpressionEnterVisitor expressionVisitor
        |> Rule.fromModuleRuleSchema


contextCreator : Rule.ContextCreator () Context
contextCreator =
    Rule.initContextCreator
        (\moduleName () -> { isExemptModule = isExempt moduleName })
        |> Rule.withModuleName


isExempt : List String -> Bool
isExempt moduleName =
    (moduleName == [ "Daisy", "Render" ])
        || (List.take 2 moduleName == [ "Daisy", "Schema" ])


expressionVisitor : Node Expression -> Context -> ( List (Rule.Error {}), Context )
expressionVisitor node context =
    if context.isExemptModule then
        ( [], context )

    else
        case Node.value node of
            Expression.Literal value ->
                if Set.member value SchemaClasses.all then
                    ( [ error value node ], context )

                else
                    ( [], context )

            _ ->
                ( [], context )


error : String -> Node Expression -> Rule.Error {}
error value node =
    Rule.error
        { message = "String literal \"" ++ value ++ "\" is a raw daisyUI class name"
        , details =
            [ "This exact string appears in fixtures/schema.json as a daisyUI class. Hand-writing a schema class as a string bypasses the typed Daisy.Tree / Daisy.Schema constructors that guarantee no contradictory modifiers or invalid nesting. Use the generated Daisy.Schema type and constructor instead; only Daisy.Render is allowed to turn those into class strings."
            ]
        }
        (Node.range node)
