module CorpusTest exposing (suite)

{-| Tier A, row 5: every daisyUI docs example is either expressed by a
hand-written `Daisy.Tree` value whose render carries the same daisyUI classes,
or listed in `fixtures/rejected.md` with a reason.

For an accepted example the test walks the fixture's elements — only those with
at least one daisyUI class — and asks whether the render contains an element
carrying _exactly_ that set of daisyUI classes. Tailwind utilities are ignored
on both sides: the docs use them for one-off layout, and the tree decides
layout itself through `Daisy.Render.tokens`. Hierarchy is checked separately by
`PartsTest`, so this row is about the class sets per element.

`Corpus.Fixtures` and `Corpus.Rejected` are generated by
`bun tools/gen-corpus-elm.js`; `Corpus.Trees` is hand-written, one entry per
accepted id.

-}

import Corpus.Fixtures as Fixtures exposing (Fixture)
import Corpus.Rejected as Rejected
import Corpus.Trees as Trees
import Daisy.Schema as Schema
import Expect
import Helpers.Classes as Classes
import Set
import Test exposing (Test, describe, test)


accepted : List Fixture
accepted =
    List.filter (\fixture -> Trees.treeFor fixture.id /= Nothing) Fixtures.all


rejectedIds : List String
rejectedIds =
    List.map .id Rejected.all


fixtureIds : List String
fixtureIds =
    List.map .id Fixtures.all


{-| The categories `fixtures/rejected.md` documents.
-}
categories : List String
categories =
    [ "inexpressible: ", "unmapped: " ]


expectFixture : Fixture -> Expect.Expectation
expectFixture fixture =
    case Trees.treeFor fixture.id of
        Nothing ->
            Expect.fail "no tree"

        Just node ->
            let
                html =
                    Trees.render node
            in
            fixture.elements
                |> List.map (\element -> ( element, Set.intersect (Set.fromList element.daisy) Schema.allClasses ))
                |> List.filter (\( _, wanted ) -> not (Set.isEmpty wanted))
                |> List.filterMap
                    (\( element, wanted ) ->
                        if Classes.hasElementWithDaisySet wanted html then
                            Nothing

                        else
                            Just
                                ("no rendered element carries exactly ["
                                    ++ String.join " " (Set.toList wanted)
                                    ++ "] (fixture element "
                                    ++ element.path
                                    ++ ", <"
                                    ++ element.tag
                                    ++ ">)"
                                )
                    )
                |> Classes.expectNoProblems


suite : Test
suite =
    describe "docs corpus"
        [ describe "accepted examples render the same daisyUI classes"
            (List.map (\fixture -> test fixture.id (\_ -> expectFixture fixture)) accepted)
        , test "every fixture is either accepted or rejected" <|
            \_ ->
                Fixtures.all
                    |> List.filter (\fixture -> Trees.treeFor fixture.id == Nothing)
                    |> List.filter (\fixture -> not (List.member fixture.id rejectedIds))
                    |> List.map (\fixture -> fixture.id ++ " has neither a tree nor a rejected.md row")
                    |> Classes.expectNoProblems
        , test "no example is both accepted and rejected" <|
            \_ ->
                accepted
                    |> List.filter (\fixture -> List.member fixture.id rejectedIds)
                    |> List.map (\fixture -> fixture.id ++ " has a tree and a rejected.md row")
                    |> Classes.expectNoProblems
        , test "every rejected id is a real fixture id" <|
            \_ ->
                rejectedIds
                    |> List.filter (\id -> not (List.member id fixtureIds))
                    |> List.map (\id -> id ++ " is in rejected.md but is not a corpus fixture")
                    |> Classes.expectNoProblems
        , test "every rejection gives a reason in a known category" <|
            \_ ->
                Rejected.all
                    |> List.filter
                        (\rejection ->
                            not (List.any (\category -> String.startsWith category rejection.reason) categories)
                        )
                    |> List.map
                        (\rejection ->
                            rejection.id
                                ++ ": reason \""
                                ++ rejection.reason
                                ++ "\" does not start with "
                                ++ String.join " or " categories
                        )
                    |> Classes.expectNoProblems
        , test "rejected.md has no duplicate rows" <|
            \_ ->
                Expect.equal (List.length rejectedIds) (Set.size (Set.fromList rejectedIds))
        ]
