-- GENERATED by tools/gen-corpus-elm.js from fixtures/rejected.md. Do not edit.


module Corpus.Rejected exposing (Rejection, all)

{-| The corpus examples the closed tree refuses, with the reason recorded in
fixtures/rejected.md.

@docs Rejection, all

-}


{-| One rejected example.
-}
type alias Rejection =
    { id : String
    , reason : String
    }


{-| Every row of the fixtures/rejected.md table.
-}
all : List Rejection
all =
    [ { id = "accordion--04", reason = "inexpressible: a `collapse` carrying `join-item`; `JoinItem` is a closed list of button, input, select and text, so a block cannot be joined" }
    , { id = "calendar--01", reason = "inexpressible: the `cally` picker itself is expressible as `Leaf.Calendar`, but this example puts it inside a `dropdown` popover, and a dropdown's content is a closed `MenuSpec` — the same rule that rejects a card as `dropdown-content`" }
    , { id = "card--15", reason = "inexpressible: a `card` carrying `join-item`; `JoinItem` is a closed list of button, input, select and text, so a block cannot be joined" }
    , { id = "drawer--01", reason = "inexpressible: a `navbar` and a horizontal `menu` inside `drawer-content`; `Overlay.Drawer` holds sections in `drawer-side` only, and its toggle button is `btn drawer-button` with no further classes" }
    , { id = "drawer--03", reason = "inexpressible: the `is-drawer-open:` / `is-drawer-close:` selector prefixes; they are Tailwind variants, not classes an element can carry (see Render.unreachableClasses)" }
    , { id = "drawer--04", reason = "inexpressible: a `btn-primary` drawer button; `btn-primary` is reserved for `Page.cta`, which the shell places, and the drawer's own button is `btn drawer-button`" }
    , { id = "dropdown--01", reason = "inexpressible: `dropdown` and `menu` on one element (popover API); the renderer always wraps the anchor in its own `dropdown` element" }
    , { id = "dropdown--07", reason = "inexpressible: two `dropdown` placement classes on one element (a corner); the schema declares `placement` as pick-at-most-one, so `DropdownConfig.placement` holds one and ExclusivityTest forbids two" }
    , { id = "dropdown--08", reason = "inexpressible: two `dropdown` placement classes on one element (a corner); the schema declares `placement` as pick-at-most-one, so `DropdownConfig.placement` holds one and ExclusivityTest forbids two" }
    , { id = "dropdown--10", reason = "inexpressible: two `dropdown` placement classes on one element (a corner); the schema declares `placement` as pick-at-most-one, so `DropdownConfig.placement` holds one and ExclusivityTest forbids two" }
    , { id = "dropdown--11", reason = "inexpressible: two `dropdown` placement classes on one element (a corner); the schema declares `placement` as pick-at-most-one, so `DropdownConfig.placement` holds one and ExclusivityTest forbids two" }
    , { id = "dropdown--13", reason = "inexpressible: two `dropdown` placement classes on one element (a corner); the schema declares `placement` as pick-at-most-one, so `DropdownConfig.placement` holds one and ExclusivityTest forbids two" }
    , { id = "dropdown--14", reason = "inexpressible: two `dropdown` placement classes on one element (a corner); the schema declares `placement` as pick-at-most-one, so `DropdownConfig.placement` holds one and ExclusivityTest forbids two" }
    , { id = "dropdown--16", reason = "inexpressible: two `dropdown` placement classes on one element (a corner); the schema declares `placement` as pick-at-most-one, so `DropdownConfig.placement` holds one and ExclusivityTest forbids two" }
    , { id = "dropdown--17", reason = "inexpressible: two `dropdown` placement classes on one element (a corner); the schema declares `placement` as pick-at-most-one, so `DropdownConfig.placement` holds one and ExclusivityTest forbids two" }
    , { id = "dropdown--21", reason = "inexpressible: a `card` as `dropdown-content`; `Dropdown` holds a `MenuSpec`, so the content of a dropdown is always a menu" }
    , { id = "dropdown--23", reason = "inexpressible: a `card` as `dropdown-content`; `Dropdown` holds a `MenuSpec`, so the content of a dropdown is always a menu" }
    , { id = "fab--00", reason = "inexpressible: the fab's main action is a `btn-primary`; `btn-primary` is reserved for `Page.cta`" }
    , { id = "fab--05", reason = "inexpressible: the fab's main action is a `btn-primary`; `btn-primary` is reserved for `Page.cta`" }
    , { id = "fab--06", reason = "inexpressible: the fab's main action is a `btn-primary`; `btn-primary` is reserved for `Page.cta`" }
    , { id = "fab--08", reason = "inexpressible: the fab's main action is a `btn-primary`; `btn-primary` is reserved for `Page.cta`" }
    , { id = "fab--09", reason = "inexpressible: the fab's main action is a `btn-primary`; `btn-primary` is reserved for `Page.cta`" }
    , { id = "footer--02", reason = "inexpressible: a `btn-primary` inside a `join`; `btn-primary` is reserved for `Page.cta`, which the shell places outside any join" }
    , { id = "indicator--03", reason = "inexpressible: `indicator` on the `tab` element itself; the renderer always emits its own `indicator` wrapper around the anchor" }
    , { id = "indicator--04", reason = "inexpressible: `indicator` on the `avatar` element itself; the renderer wraps the avatar in its own `indicator` element" }
    , { id = "indicator--06", reason = "inexpressible: a button as the `indicator-item`; `IndicatorPayload` is a badge or a status" }
    , { id = "indicator--07", reason = "inexpressible: two `indicator` placement classes on one element (a corner); the schema declares `placement` as pick-at-most-one" }
    , { id = "indicator--11", reason = "inexpressible: two `indicator` placement classes on one element (a corner); the schema declares `placement` as pick-at-most-one" }
    , { id = "indicator--12", reason = "inexpressible: two `indicator` placement classes on one element (a corner); the schema declares `placement` as pick-at-most-one" }
    , { id = "indicator--14", reason = "inexpressible: two `indicator` placement classes on one element (a corner); the schema declares `placement` as pick-at-most-one" }
    , { id = "indicator--15", reason = "inexpressible: two `indicator` placement classes on one element (a corner); the schema declares `placement` as pick-at-most-one" }
    , { id = "indicator--17", reason = "inexpressible: two `indicator` placement classes on one element (a corner); the schema declares `placement` as pick-at-most-one" }
    , { id = "input--15", reason = "inexpressible: `validator` on one input inside a `join`; `Field.validate` marks the whole control, which here is the join" }
    , { id = "menu--05", reason = "inexpressible: a tooltip on a menu item; `tooltip` is a field on leaf configs and `MenuItem` is not a leaf" }
    , { id = "menu--06", reason = "inexpressible: a tooltip on a menu item; `tooltip` is a field on leaf configs and `MenuItem` is not a leaf" }
    , { id = "menu--16", reason = "inexpressible: `menu-dropdown-show` on an item's toggle and submenu, but `MenuConfig.modifiers` puts menu modifiers on the `menu` container" }
    , { id = "navbar--03", reason = "inexpressible: a horizontal `menu` inside a `navbar`; `Section.Navbar` holds leaves and `Menu` is a block (a known gap recorded in docs/placement.md)" }
    , { id = "navbar--04", reason = "inexpressible: `avatar` and `btn` on one element; `Leaf.Avatar` always renders its own `avatar` element" }
    , { id = "navbar--05", reason = "inexpressible: `avatar` and `btn` on one element; `Leaf.Avatar` always renders its own `avatar` element" }
    , { id = "navbar--07", reason = "inexpressible: a horizontal `menu` inside a `navbar`; `Section.Navbar` holds leaves and `Menu` is a block (a known gap recorded in docs/placement.md)" }
    , { id = "navbar--08", reason = "inexpressible: a `navbar` carrying `collapse-title`; `collapse` parts belong to `Block.Collapse` and a section cannot sit inside a block" }
    , { id = "stack--02", reason = "inexpressible: `card` blocks inside a `stack`; `Block.Stacked` holds leaves, and a block cannot contain another block" }
    , { id = "stack--03", reason = "inexpressible: `card` blocks inside a `stack`; `Block.Stacked` holds leaves, and a block cannot contain another block" }
    , { id = "stack--04", reason = "inexpressible: `card` blocks inside a `stack`; `Block.Stacked` holds leaves, and a block cannot contain another block" }
    , { id = "stack--05", reason = "inexpressible: `card` blocks inside a `stack`; `Block.Stacked` holds leaves, and a block cannot contain another block" }
    , { id = "stack--06", reason = "inexpressible: `card` blocks inside a `stack`; `Block.Stacked` holds leaves, and a block cannot contain another block" }
    , { id = "stack--07", reason = "inexpressible: `card` blocks inside a `stack`; `Block.Stacked` holds leaves, and a block cannot contain another block" }
    , { id = "swap--03", reason = "inexpressible: `swap` and `btn` on one element; `Leaf.Swap` always renders its own `swap` label" }
    , { id = "theme-controller--02", reason = "inexpressible: a `theme-controller` swap with `swap-on` / `swap-off` faces; `ThemeSelect` renders the controller as one input per theme, with no faces" }
    , { id = "theme-controller--05", reason = "inexpressible: `theme-controller` and `toggle` on separate elements; `ThemeSelect` emits both classes on one input" }
    , { id = "theme-controller--07", reason = "inexpressible: a sized `radio theme-controller`; `ThemeSelectData` has no size field" }
    , { id = "theme-controller--08", reason = "inexpressible: a `theme-controller` carrying `join-item`; `ThemeSelect` is a leaf of its own and cannot be a `JoinItem`" }
    , { id = "toast--01", reason = "inexpressible: a horizontal and a vertical `toast` placement on one element (a corner); the schema declares `placement` as pick-at-most-one" }
    , { id = "toast--02", reason = "inexpressible: a horizontal and a vertical `toast` placement on one element (a corner); the schema declares `placement` as pick-at-most-one" }
    , { id = "toast--03", reason = "inexpressible: a horizontal and a vertical `toast` placement on one element (a corner); the schema declares `placement` as pick-at-most-one" }
    , { id = "toast--04", reason = "inexpressible: a horizontal and a vertical `toast` placement on one element (a corner); the schema declares `placement` as pick-at-most-one" }
    , { id = "toast--05", reason = "inexpressible: a horizontal and a vertical `toast` placement on one element (a corner); the schema declares `placement` as pick-at-most-one" }
    , { id = "toast--06", reason = "inexpressible: a horizontal and a vertical `toast` placement on one element (a corner); the schema declares `placement` as pick-at-most-one" }
    , { id = "tooltip--03", reason = "inexpressible: two `tooltip` placement classes on one element (a corner); the schema declares `placement` as pick-at-most-one" }
    , { id = "tooltip--04", reason = "inexpressible: two `tooltip` placement classes on one element (a corner); the schema declares `placement` as pick-at-most-one" }
    , { id = "tooltip--05", reason = "inexpressible: two `tooltip` placement classes on one element (a corner); the schema declares `placement` as pick-at-most-one" }
    , { id = "tooltip--06", reason = "inexpressible: two `tooltip` placement classes on one element (a corner); the schema declares `placement` as pick-at-most-one" }
    ]
