-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Alert exposing
    ( Color(..), Direction(..), Style(..)
    , allColors, allDirections, allStyles, colorToClass, component, componentClasses, directionToClass, parts, styleToClass
    )

{-| Generated schema for the daisyUI `alert` component.

@docs Color, Direction, Style

@docs allColors, allDirections, allStyles, colorToClass, component, componentClasses, directionToClass, parts, styleToClass

-}


{-| The main daisyUI class of the `alert` component.
-}
component : String
component =
    "alert"


{-| Every class in the `component` group of `alert`.
-}
componentClasses : List String
componentClasses =
    [ "alert"
    ]


{-| Every class in the `part` group of `alert`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []


{-| The `color` group of `alert`. At most one value may be applied.
-}
type Color
    = Info
    | Success
    | Warning
    | Error


{-| Every [`Color`](#Color) value.
-}
allColors : List Color
allColors =
    [ Info
    , Success
    , Warning
    , Error
    ]


{-| The daisyUI class for a [`Color`](#Color).
-}
colorToClass : Color -> String
colorToClass value =
    case value of
        Info ->
            "alert-info"

        Success ->
            "alert-success"

        Warning ->
            "alert-warning"

        Error ->
            "alert-error"


{-| The `style` group of `alert`. At most one value may be applied.
-}
type Style
    = Outline
    | Dash
    | Soft


{-| Every [`Style`](#Style) value.
-}
allStyles : List Style
allStyles =
    [ Outline
    , Dash
    , Soft
    ]


{-| The daisyUI class for a [`Style`](#Style).
-}
styleToClass : Style -> String
styleToClass value =
    case value of
        Outline ->
            "alert-outline"

        Dash ->
            "alert-dash"

        Soft ->
            "alert-soft"


{-| The `direction` group of `alert`. At most one value may be applied.
-}
type Direction
    = Vertical
    | Horizontal


{-| Every [`Direction`](#Direction) value.
-}
allDirections : List Direction
allDirections =
    [ Vertical
    , Horizontal
    ]


{-| The daisyUI class for a [`Direction`](#Direction).
-}
directionToClass : Direction -> String
directionToClass value =
    case value of
        Vertical ->
            "alert-vertical"

        Horizontal ->
            "alert-horizontal"
