-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Aura exposing
    ( Size(..), Style(..)
    , allSizes, allStyles, component, componentClasses, parts, sizeToClass, styleToClass
    )

{-| Generated schema for the daisyUI `aura` component.

@docs Size, Style

@docs allSizes, allStyles, component, componentClasses, parts, sizeToClass, styleToClass

-}


{-| The main daisyUI class of the `aura` component.
-}
component : String
component =
    "aura"


{-| Every class in the `component` group of `aura`.
-}
componentClasses : List String
componentClasses =
    [ "aura"
    ]


{-| Every class in the `part` group of `aura`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []


{-| The `style` group of `aura`. At most one value may be applied.
-}
type Style
    = Dual
    | Rainbow
    | Holo
    | Gold
    | Silver
    | Glow


{-| Every [`Style`](#Style) value.
-}
allStyles : List Style
allStyles =
    [ Dual
    , Rainbow
    , Holo
    , Gold
    , Silver
    , Glow
    ]


{-| The daisyUI class for a [`Style`](#Style).
-}
styleToClass : Style -> String
styleToClass value =
    case value of
        Dual ->
            "aura-dual"

        Rainbow ->
            "aura-rainbow"

        Holo ->
            "aura-holo"

        Gold ->
            "aura-gold"

        Silver ->
            "aura-silver"

        Glow ->
            "aura-glow"


{-| The `size` group of `aura`. At most one value may be applied.
-}
type Size
    = Xs
    | Sm
    | Md
    | Lg
    | Xl


{-| Every [`Size`](#Size) value.
-}
allSizes : List Size
allSizes =
    [ Xs
    , Sm
    , Md
    , Lg
    , Xl
    ]


{-| The daisyUI class for a [`Size`](#Size).
-}
sizeToClass : Size -> String
sizeToClass value =
    case value of
        Xs ->
            "aura-xs"

        Sm ->
            "aura-sm"

        Md ->
            "aura-md"

        Lg ->
            "aura-lg"

        Xl ->
            "aura-xl"
