-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Avatar exposing
    ( Modifier(..)
    , allModifiers, component, componentClasses, modifierToClass, parts
    )

{-| Generated schema for the daisyUI `avatar` component.

@docs Modifier

@docs allModifiers, component, componentClasses, modifierToClass, parts

-}


{-| The main daisyUI class of the `avatar` component.
-}
component : String
component =
    "avatar"


{-| Every class in the `component` group of `avatar`.
-}
componentClasses : List String
componentClasses =
    [ "avatar"
    , "avatar-group"
    ]


{-| Every class in the `part` group of `avatar`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []


{-| The `modifier` group of `avatar`. Any number of values may be applied.
-}
type Modifier
    = Online
    | Offline
    | Placeholder


{-| Every [`Modifier`](#Modifier) value.
-}
allModifiers : List Modifier
allModifiers =
    [ Online
    , Offline
    , Placeholder
    ]


{-| The daisyUI class for a [`Modifier`](#Modifier).
-}
modifierToClass : Modifier -> String
modifierToClass value =
    case value of
        Online ->
            "avatar-online"

        Offline ->
            "avatar-offline"

        Placeholder ->
            "avatar-placeholder"
