-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Badge exposing
    ( Color(..), Size(..), Style(..)
    , allColors, allSizes, allStyles, colorToClass, component, componentClasses, parts, sizeToClass, styleToClass
    )

{-| Generated schema for the daisyUI `badge` component.

@docs Color, Size, Style

@docs allColors, allSizes, allStyles, colorToClass, component, componentClasses, parts, sizeToClass, styleToClass

-}


{-| The main daisyUI class of the `badge` component.
-}
component : String
component =
    "badge"


{-| Every class in the `component` group of `badge`.
-}
componentClasses : List String
componentClasses =
    [ "badge"
    ]


{-| Every class in the `part` group of `badge`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []


{-| The `color` group of `badge`. At most one value may be applied.
-}
type Color
    = Neutral
    | Primary
    | Secondary
    | Accent
    | Info
    | Success
    | Warning
    | Error


{-| Every [`Color`](#Color) value.
-}
allColors : List Color
allColors =
    [ Neutral
    , Primary
    , Secondary
    , Accent
    , Info
    , Success
    , Warning
    , Error
    ]


{-| The daisyUI class for a [`Color`](#Color).
-}
colorToClass : Color -> String
colorToClass value =
    case value of
        Neutral ->
            "badge-neutral"

        Primary ->
            "badge-primary"

        Secondary ->
            "badge-secondary"

        Accent ->
            "badge-accent"

        Info ->
            "badge-info"

        Success ->
            "badge-success"

        Warning ->
            "badge-warning"

        Error ->
            "badge-error"


{-| The `style` group of `badge`. At most one value may be applied.
-}
type Style
    = Outline
    | Dash
    | Soft
    | Ghost


{-| Every [`Style`](#Style) value.
-}
allStyles : List Style
allStyles =
    [ Outline
    , Dash
    , Soft
    , Ghost
    ]


{-| The daisyUI class for a [`Style`](#Style).
-}
styleToClass : Style -> String
styleToClass value =
    case value of
        Outline ->
            "badge-outline"

        Dash ->
            "badge-dash"

        Soft ->
            "badge-soft"

        Ghost ->
            "badge-ghost"


{-| The `size` group of `badge`. At most one value may be applied.
-}
type Size
    = Xs
    | Sm
    | Md
    | Lg
    | Xl


{-| Every [`Size`](#Size) value.
-}
allSizes : List Size
allSizes =
    [ Xs
    , Sm
    , Md
    , Lg
    , Xl
    ]


{-| The daisyUI class for a [`Size`](#Size).
-}
sizeToClass : Size -> String
sizeToClass value =
    case value of
        Xs ->
            "badge-xs"

        Sm ->
            "badge-sm"

        Md ->
            "badge-md"

        Lg ->
            "badge-lg"

        Xl ->
            "badge-xl"
