-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Breadcrumbs exposing (component, componentClasses, parts)

{-| Generated schema for the daisyUI `breadcrumbs` component.

@docs component, componentClasses, parts

-}


{-| The main daisyUI class of the `breadcrumbs` component.
-}
component : String
component =
    "breadcrumbs"


{-| Every class in the `component` group of `breadcrumbs`.
-}
componentClasses : List String
componentClasses =
    [ "breadcrumbs"
    ]


{-| Every class in the `part` group of `breadcrumbs`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []
