-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Button exposing
    ( Behavior(..), Color(..), Modifier(..), Size(..), Style(..)
    , allBehaviors, allColors, allModifiers, allSizes, allStyles, behaviorToClass, colorToClass, component, componentClasses, modifierToClass, parts, sizeToClass, styleToClass
    )

{-| Generated schema for the daisyUI `button` component.

@docs Behavior, Color, Modifier, Size, Style

@docs allBehaviors, allColors, allModifiers, allSizes, allStyles, behaviorToClass, colorToClass, component, componentClasses, modifierToClass, parts, sizeToClass, styleToClass

-}


{-| The main daisyUI class of the `button` component.
-}
component : String
component =
    "btn"


{-| Every class in the `component` group of `button`.
-}
componentClasses : List String
componentClasses =
    [ "btn"
    ]


{-| Every class in the `part` group of `button`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []


{-| The `color` group of `button`. At most one value may be applied.
-}
type Color
    = Neutral
    | Primary
    | Secondary
    | Accent
    | Info
    | Success
    | Warning
    | Error


{-| Every [`Color`](#Color) value.
-}
allColors : List Color
allColors =
    [ Neutral
    , Primary
    , Secondary
    , Accent
    , Info
    , Success
    , Warning
    , Error
    ]


{-| The daisyUI class for a [`Color`](#Color).
-}
colorToClass : Color -> String
colorToClass value =
    case value of
        Neutral ->
            "btn-neutral"

        Primary ->
            "btn-primary"

        Secondary ->
            "btn-secondary"

        Accent ->
            "btn-accent"

        Info ->
            "btn-info"

        Success ->
            "btn-success"

        Warning ->
            "btn-warning"

        Error ->
            "btn-error"


{-| The `style` group of `button`. At most one value may be applied.
-}
type Style
    = Outline
    | Dash
    | Soft
    | Ghost
    | Link


{-| Every [`Style`](#Style) value.
-}
allStyles : List Style
allStyles =
    [ Outline
    , Dash
    , Soft
    , Ghost
    , Link
    ]


{-| The daisyUI class for a [`Style`](#Style).
-}
styleToClass : Style -> String
styleToClass value =
    case value of
        Outline ->
            "btn-outline"

        Dash ->
            "btn-dash"

        Soft ->
            "btn-soft"

        Ghost ->
            "btn-ghost"

        Link ->
            "btn-link"


{-| The `size` group of `button`. At most one value may be applied.
-}
type Size
    = Xs
    | Sm
    | Md
    | Lg
    | Xl


{-| Every [`Size`](#Size) value.
-}
allSizes : List Size
allSizes =
    [ Xs
    , Sm
    , Md
    , Lg
    , Xl
    ]


{-| The daisyUI class for a [`Size`](#Size).
-}
sizeToClass : Size -> String
sizeToClass value =
    case value of
        Xs ->
            "btn-xs"

        Sm ->
            "btn-sm"

        Md ->
            "btn-md"

        Lg ->
            "btn-lg"

        Xl ->
            "btn-xl"


{-| The `modifier` group of `button`. Any number of values may be applied.
-}
type Modifier
    = Wide
    | Block
    | Square
    | Circle


{-| Every [`Modifier`](#Modifier) value.
-}
allModifiers : List Modifier
allModifiers =
    [ Wide
    , Block
    , Square
    , Circle
    ]


{-| The daisyUI class for a [`Modifier`](#Modifier).
-}
modifierToClass : Modifier -> String
modifierToClass value =
    case value of
        Wide ->
            "btn-wide"

        Block ->
            "btn-block"

        Square ->
            "btn-square"

        Circle ->
            "btn-circle"


{-| The `behavior` group of `button`. Any number of values may be applied.
-}
type Behavior
    = Active
    | Disabled


{-| Every [`Behavior`](#Behavior) value.
-}
allBehaviors : List Behavior
allBehaviors =
    [ Active
    , Disabled
    ]


{-| The daisyUI class for a [`Behavior`](#Behavior).
-}
behaviorToClass : Behavior -> String
behaviorToClass value =
    case value of
        Active ->
            "btn-active"

        Disabled ->
            "btn-disabled"
