-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Calendar exposing (component, componentClasses, parts)

{-| Generated schema for the daisyUI `calendar` component.

@docs component, componentClasses, parts

-}


{-| The main daisyUI class of the `calendar` component.
-}
component : String
component =
    "cally"


{-| Every class in the `component` group of `calendar`.
-}
componentClasses : List String
componentClasses =
    [ "cally"
    , "react-day-picker"
    , "vc"
    ]


{-| Every class in the `part` group of `calendar`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []
