-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Card exposing
    ( Modifier(..), Size(..), Style(..)
    , allModifiers, allSizes, allStyles, component, componentClasses, modifierToClass, parts, sizeToClass, styleToClass
    )

{-| Generated schema for the daisyUI `card` component.

@docs Modifier, Size, Style

@docs allModifiers, allSizes, allStyles, component, componentClasses, modifierToClass, parts, sizeToClass, styleToClass

-}


{-| The main daisyUI class of the `card` component.
-}
component : String
component =
    "card"


{-| Every class in the `component` group of `card`.
-}
componentClasses : List String
componentClasses =
    [ "card"
    ]


{-| Every class in the `part` group of `card`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    [ "card-title"
    , "card-body"
    , "card-actions"
    ]


{-| The `style` group of `card`. At most one value may be applied.
-}
type Style
    = Border
    | Dash


{-| Every [`Style`](#Style) value.
-}
allStyles : List Style
allStyles =
    [ Border
    , Dash
    ]


{-| The daisyUI class for a [`Style`](#Style).
-}
styleToClass : Style -> String
styleToClass value =
    case value of
        Border ->
            "card-border"

        Dash ->
            "card-dash"


{-| The `size` group of `card`. At most one value may be applied.
-}
type Size
    = Xs
    | Sm
    | Md
    | Lg
    | Xl


{-| Every [`Size`](#Size) value.
-}
allSizes : List Size
allSizes =
    [ Xs
    , Sm
    , Md
    , Lg
    , Xl
    ]


{-| The daisyUI class for a [`Size`](#Size).
-}
sizeToClass : Size -> String
sizeToClass value =
    case value of
        Xs ->
            "card-xs"

        Sm ->
            "card-sm"

        Md ->
            "card-md"

        Lg ->
            "card-lg"

        Xl ->
            "card-xl"


{-| The `modifier` group of `card`. Any number of values may be applied.
-}
type Modifier
    = Side
    | ImageFull


{-| Every [`Modifier`](#Modifier) value.
-}
allModifiers : List Modifier
allModifiers =
    [ Side
    , ImageFull
    ]


{-| The daisyUI class for a [`Modifier`](#Modifier).
-}
modifierToClass : Modifier -> String
modifierToClass value =
    case value of
        Side ->
            "card-side"

        ImageFull ->
            "image-full"
