-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Carousel exposing
    ( Direction(..), Modifier(..)
    , allDirections, allModifiers, component, componentClasses, directionToClass, modifierToClass, parts
    )

{-| Generated schema for the daisyUI `carousel` component.

@docs Direction, Modifier

@docs allDirections, allModifiers, component, componentClasses, directionToClass, modifierToClass, parts

-}


{-| The main daisyUI class of the `carousel` component.
-}
component : String
component =
    "carousel"


{-| Every class in the `component` group of `carousel`.
-}
componentClasses : List String
componentClasses =
    [ "carousel"
    ]


{-| Every class in the `part` group of `carousel`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    [ "carousel-item"
    ]


{-| The `direction` group of `carousel`. At most one value may be applied.
-}
type Direction
    = Horizontal
    | Vertical


{-| Every [`Direction`](#Direction) value.
-}
allDirections : List Direction
allDirections =
    [ Horizontal
    , Vertical
    ]


{-| The daisyUI class for a [`Direction`](#Direction).
-}
directionToClass : Direction -> String
directionToClass value =
    case value of
        Horizontal ->
            "carousel-horizontal"

        Vertical ->
            "carousel-vertical"


{-| The `modifier` group of `carousel`. Any number of values may be applied.
-}
type Modifier
    = Start
    | Center
    | End


{-| Every [`Modifier`](#Modifier) value.
-}
allModifiers : List Modifier
allModifiers =
    [ Start
    , Center
    , End
    ]


{-| The daisyUI class for a [`Modifier`](#Modifier).
-}
modifierToClass : Modifier -> String
modifierToClass value =
    case value of
        Start ->
            "carousel-start"

        Center ->
            "carousel-center"

        End ->
            "carousel-end"
