-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Chat exposing
    ( Color(..), Placement(..)
    , allColors, allPlacements, colorToClass, component, componentClasses, parts, placementToClass
    )

{-| Generated schema for the daisyUI `chat` component.

@docs Color, Placement

@docs allColors, allPlacements, colorToClass, component, componentClasses, parts, placementToClass

-}


{-| The main daisyUI class of the `chat` component.
-}
component : String
component =
    "chat"


{-| Every class in the `component` group of `chat`.
-}
componentClasses : List String
componentClasses =
    [ "chat"
    ]


{-| Every class in the `part` group of `chat`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    [ "chat-image"
    , "chat-header"
    , "chat-footer"
    , "chat-bubble"
    ]


{-| The `color` group of `chat`. At most one value may be applied.
-}
type Color
    = Neutral
    | Primary
    | Secondary
    | Accent
    | Info
    | Success
    | Warning
    | Error


{-| Every [`Color`](#Color) value.
-}
allColors : List Color
allColors =
    [ Neutral
    , Primary
    , Secondary
    , Accent
    , Info
    , Success
    , Warning
    , Error
    ]


{-| The daisyUI class for a [`Color`](#Color).
-}
colorToClass : Color -> String
colorToClass value =
    case value of
        Neutral ->
            "chat-bubble-neutral"

        Primary ->
            "chat-bubble-primary"

        Secondary ->
            "chat-bubble-secondary"

        Accent ->
            "chat-bubble-accent"

        Info ->
            "chat-bubble-info"

        Success ->
            "chat-bubble-success"

        Warning ->
            "chat-bubble-warning"

        Error ->
            "chat-bubble-error"


{-| The `placement` group of `chat`. At most one value may be applied.
-}
type Placement
    = Start
    | End


{-| Every [`Placement`](#Placement) value.
-}
allPlacements : List Placement
allPlacements =
    [ Start
    , End
    ]


{-| The daisyUI class for a [`Placement`](#Placement).
-}
placementToClass : Placement -> String
placementToClass value =
    case value of
        Start ->
            "chat-start"

        End ->
            "chat-end"
