-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Collapse exposing
    ( Modifier(..)
    , allModifiers, component, componentClasses, modifierToClass, parts
    )

{-| Generated schema for the daisyUI `collapse` component.

@docs Modifier

@docs allModifiers, component, componentClasses, modifierToClass, parts

-}


{-| The main daisyUI class of the `collapse` component.
-}
component : String
component =
    "collapse"


{-| Every class in the `component` group of `collapse`.
-}
componentClasses : List String
componentClasses =
    [ "collapse"
    ]


{-| Every class in the `part` group of `collapse`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    [ "collapse-title"
    , "collapse-content"
    ]


{-| The `modifier` group of `collapse`. Any number of values may be applied.
-}
type Modifier
    = Arrow
    | Plus
    | Open
    | Close


{-| Every [`Modifier`](#Modifier) value.
-}
allModifiers : List Modifier
allModifiers =
    [ Arrow
    , Plus
    , Open
    , Close
    ]


{-| The daisyUI class for a [`Modifier`](#Modifier).
-}
modifierToClass : Modifier -> String
modifierToClass value =
    case value of
        Arrow ->
            "collapse-arrow"

        Plus ->
            "collapse-plus"

        Open ->
            "collapse-open"

        Close ->
            "collapse-close"
