-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Countdown exposing (component, componentClasses, parts)

{-| Generated schema for the daisyUI `countdown` component.

@docs component, componentClasses, parts

-}


{-| The main daisyUI class of the `countdown` component.
-}
component : String
component =
    "countdown"


{-| Every class in the `component` group of `countdown`.
-}
componentClasses : List String
componentClasses =
    [ "countdown"
    ]


{-| Every class in the `part` group of `countdown`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []
