-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Diff exposing (component, componentClasses, parts)

{-| Generated schema for the daisyUI `diff` component.

@docs component, componentClasses, parts

-}


{-| The main daisyUI class of the `diff` component.
-}
component : String
component =
    "diff"


{-| Every class in the `component` group of `diff`.
-}
componentClasses : List String
componentClasses =
    [ "diff"
    ]


{-| Every class in the `part` group of `diff`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    [ "diff-item-1"
    , "diff-item-2"
    , "diff-resizer"
    ]
