-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Divider exposing
    ( Color(..), Direction(..), Placement(..)
    , allColors, allDirections, allPlacements, colorToClass, component, componentClasses, directionToClass, parts, placementToClass
    )

{-| Generated schema for the daisyUI `divider` component.

@docs Color, Direction, Placement

@docs allColors, allDirections, allPlacements, colorToClass, component, componentClasses, directionToClass, parts, placementToClass

-}


{-| The main daisyUI class of the `divider` component.
-}
component : String
component =
    "divider"


{-| Every class in the `component` group of `divider`.
-}
componentClasses : List String
componentClasses =
    [ "divider"
    ]


{-| Every class in the `part` group of `divider`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []


{-| The `color` group of `divider`. At most one value may be applied.
-}
type Color
    = Neutral
    | Primary
    | Secondary
    | Accent
    | Success
    | Warning
    | Info
    | Error


{-| Every [`Color`](#Color) value.
-}
allColors : List Color
allColors =
    [ Neutral
    , Primary
    , Secondary
    , Accent
    , Success
    , Warning
    , Info
    , Error
    ]


{-| The daisyUI class for a [`Color`](#Color).
-}
colorToClass : Color -> String
colorToClass value =
    case value of
        Neutral ->
            "divider-neutral"

        Primary ->
            "divider-primary"

        Secondary ->
            "divider-secondary"

        Accent ->
            "divider-accent"

        Success ->
            "divider-success"

        Warning ->
            "divider-warning"

        Info ->
            "divider-info"

        Error ->
            "divider-error"


{-| The `direction` group of `divider`. At most one value may be applied.
-}
type Direction
    = Vertical
    | Horizontal


{-| Every [`Direction`](#Direction) value.
-}
allDirections : List Direction
allDirections =
    [ Vertical
    , Horizontal
    ]


{-| The daisyUI class for a [`Direction`](#Direction).
-}
directionToClass : Direction -> String
directionToClass value =
    case value of
        Vertical ->
            "divider-vertical"

        Horizontal ->
            "divider-horizontal"


{-| The `placement` group of `divider`. At most one value may be applied.
-}
type Placement
    = Start
    | End


{-| Every [`Placement`](#Placement) value.
-}
allPlacements : List Placement
allPlacements =
    [ Start
    , End
    ]


{-| The daisyUI class for a [`Placement`](#Placement).
-}
placementToClass : Placement -> String
placementToClass value =
    case value of
        Start ->
            "divider-start"

        End ->
            "divider-end"
