-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Dock exposing
    ( Modifier(..), Size(..)
    , allModifiers, allSizes, component, componentClasses, modifierToClass, parts, sizeToClass
    )

{-| Generated schema for the daisyUI `dock` component.

@docs Modifier, Size

@docs allModifiers, allSizes, component, componentClasses, modifierToClass, parts, sizeToClass

-}


{-| The main daisyUI class of the `dock` component.
-}
component : String
component =
    "dock"


{-| Every class in the `component` group of `dock`.
-}
componentClasses : List String
componentClasses =
    [ "dock"
    ]


{-| Every class in the `part` group of `dock`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    [ "dock-label"
    ]


{-| The `size` group of `dock`. At most one value may be applied.
-}
type Size
    = Xs
    | Sm
    | Md
    | Lg
    | Xl


{-| Every [`Size`](#Size) value.
-}
allSizes : List Size
allSizes =
    [ Xs
    , Sm
    , Md
    , Lg
    , Xl
    ]


{-| The daisyUI class for a [`Size`](#Size).
-}
sizeToClass : Size -> String
sizeToClass value =
    case value of
        Xs ->
            "dock-xs"

        Sm ->
            "dock-sm"

        Md ->
            "dock-md"

        Lg ->
            "dock-lg"

        Xl ->
            "dock-xl"


{-| The `modifier` group of `dock`. Any number of values may be applied.
-}
type Modifier
    = Active


{-| Every [`Modifier`](#Modifier) value.
-}
allModifiers : List Modifier
allModifiers =
    [ Active
    ]


{-| The daisyUI class for a [`Modifier`](#Modifier).
-}
modifierToClass : Modifier -> String
modifierToClass value =
    case value of
        Active ->
            "dock-active"
