-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Drawer exposing
    ( Modifier(..), Placement(..), Variant(..)
    , allModifiers, allPlacements, allVariants, component, componentClasses, modifierToClass, parts, placementToClass, variantToClass
    )

{-| Generated schema for the daisyUI `drawer` component.

@docs Modifier, Placement, Variant

@docs allModifiers, allPlacements, allVariants, component, componentClasses, modifierToClass, parts, placementToClass, variantToClass

-}


{-| The main daisyUI class of the `drawer` component.
-}
component : String
component =
    "drawer"


{-| Every class in the `component` group of `drawer`.
-}
componentClasses : List String
componentClasses =
    [ "drawer"
    ]


{-| Every class in the `part` group of `drawer`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    [ "drawer-toggle"
    , "drawer-content"
    , "drawer-side"
    , "drawer-overlay"
    , "drawer-button"
    ]


{-| The `placement` group of `drawer`. At most one value may be applied.
-}
type Placement
    = End


{-| Every [`Placement`](#Placement) value.
-}
allPlacements : List Placement
allPlacements =
    [ End
    ]


{-| The daisyUI class for a [`Placement`](#Placement).
-}
placementToClass : Placement -> String
placementToClass value =
    case value of
        End ->
            "drawer-end"


{-| The `variant` group of `drawer`. At most one value may be applied.
-}
type Variant
    = IsDrawerOpen
    | IsDrawerClose


{-| Every [`Variant`](#Variant) value.
-}
allVariants : List Variant
allVariants =
    [ IsDrawerOpen
    , IsDrawerClose
    ]


{-| The daisyUI class for a [`Variant`](#Variant).
-}
variantToClass : Variant -> String
variantToClass value =
    case value of
        IsDrawerOpen ->
            "is-drawer-open:"

        IsDrawerClose ->
            "is-drawer-close:"


{-| The `modifier` group of `drawer`. Any number of values may be applied.
-}
type Modifier
    = Open


{-| Every [`Modifier`](#Modifier) value.
-}
allModifiers : List Modifier
allModifiers =
    [ Open
    ]


{-| The daisyUI class for a [`Modifier`](#Modifier).
-}
modifierToClass : Modifier -> String
modifierToClass value =
    case value of
        Open ->
            "drawer-open"
