-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Dropdown exposing
    ( Modifier(..), Placement(..)
    , allModifiers, allPlacements, component, componentClasses, modifierToClass, parts, placementToClass
    )

{-| Generated schema for the daisyUI `dropdown` component.

@docs Modifier, Placement

@docs allModifiers, allPlacements, component, componentClasses, modifierToClass, parts, placementToClass

-}


{-| The main daisyUI class of the `dropdown` component.
-}
component : String
component =
    "dropdown"


{-| Every class in the `component` group of `dropdown`.
-}
componentClasses : List String
componentClasses =
    [ "dropdown"
    ]


{-| Every class in the `part` group of `dropdown`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    [ "dropdown-content"
    ]


{-| The `placement` group of `dropdown`. At most one value may be applied.
-}
type Placement
    = Start
    | Center
    | End
    | Top
    | Bottom
    | Left
    | Right


{-| Every [`Placement`](#Placement) value.
-}
allPlacements : List Placement
allPlacements =
    [ Start
    , Center
    , End
    , Top
    , Bottom
    , Left
    , Right
    ]


{-| The daisyUI class for a [`Placement`](#Placement).
-}
placementToClass : Placement -> String
placementToClass value =
    case value of
        Start ->
            "dropdown-start"

        Center ->
            "dropdown-center"

        End ->
            "dropdown-end"

        Top ->
            "dropdown-top"

        Bottom ->
            "dropdown-bottom"

        Left ->
            "dropdown-left"

        Right ->
            "dropdown-right"


{-| The `modifier` group of `dropdown`. Any number of values may be applied.
-}
type Modifier
    = Hover
    | Open
    | Close


{-| Every [`Modifier`](#Modifier) value.
-}
allModifiers : List Modifier
allModifiers =
    [ Hover
    , Open
    , Close
    ]


{-| The daisyUI class for a [`Modifier`](#Modifier).
-}
modifierToClass : Modifier -> String
modifierToClass value =
    case value of
        Hover ->
            "dropdown-hover"

        Open ->
            "dropdown-open"

        Close ->
            "dropdown-close"
