-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Fab exposing
    ( Modifier(..)
    , allModifiers, component, componentClasses, modifierToClass, parts
    )

{-| Generated schema for the daisyUI `fab` component.

@docs Modifier

@docs allModifiers, component, componentClasses, modifierToClass, parts

-}


{-| The main daisyUI class of the `fab` component.
-}
component : String
component =
    "fab"


{-| Every class in the `component` group of `fab`.
-}
componentClasses : List String
componentClasses =
    [ "fab"
    ]


{-| Every class in the `part` group of `fab`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    [ "fab-close"
    , "fab-main-action"
    ]


{-| The `modifier` group of `fab`. Any number of values may be applied.
-}
type Modifier
    = Flower


{-| Every [`Modifier`](#Modifier) value.
-}
allModifiers : List Modifier
allModifiers =
    [ Flower
    ]


{-| The daisyUI class for a [`Modifier`](#Modifier).
-}
modifierToClass : Modifier -> String
modifierToClass value =
    case value of
        Flower ->
            "fab-flower"
