-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Fieldset exposing (component, componentClasses, parts)

{-| Generated schema for the daisyUI `fieldset` component.

@docs component, componentClasses, parts

-}


{-| The main daisyUI class of the `fieldset` component.
-}
component : String
component =
    "fieldset"


{-| Every class in the `component` group of `fieldset`.
-}
componentClasses : List String
componentClasses =
    [ "fieldset"
    , "label"
    ]


{-| Every class in the `part` group of `fieldset`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    [ "fieldset-legend"
    ]
