-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Filter exposing (component, componentClasses, parts)

{-| Generated schema for the daisyUI `filter` component.

@docs component, componentClasses, parts

-}


{-| The main daisyUI class of the `filter` component.
-}
component : String
component =
    "filter"


{-| Every class in the `component` group of `filter`.
-}
componentClasses : List String
componentClasses =
    [ "filter"
    ]


{-| Every class in the `part` group of `filter`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    [ "filter-reset"
    ]
