-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Footer exposing
    ( Direction(..), Placement(..)
    , allDirections, allPlacements, component, componentClasses, directionToClass, parts, placementToClass
    )

{-| Generated schema for the daisyUI `footer` component.

@docs Direction, Placement

@docs allDirections, allPlacements, component, componentClasses, directionToClass, parts, placementToClass

-}


{-| The main daisyUI class of the `footer` component.
-}
component : String
component =
    "footer"


{-| Every class in the `component` group of `footer`.
-}
componentClasses : List String
componentClasses =
    [ "footer"
    ]


{-| Every class in the `part` group of `footer`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    [ "footer-title"
    ]


{-| The `direction` group of `footer`. At most one value may be applied.
-}
type Direction
    = Horizontal
    | Vertical


{-| Every [`Direction`](#Direction) value.
-}
allDirections : List Direction
allDirections =
    [ Horizontal
    , Vertical
    ]


{-| The daisyUI class for a [`Direction`](#Direction).
-}
directionToClass : Direction -> String
directionToClass value =
    case value of
        Horizontal ->
            "footer-horizontal"

        Vertical ->
            "footer-vertical"


{-| The `placement` group of `footer`. At most one value may be applied.
-}
type Placement
    = Center


{-| Every [`Placement`](#Placement) value.
-}
allPlacements : List Placement
allPlacements =
    [ Center
    ]


{-| The daisyUI class for a [`Placement`](#Placement).
-}
placementToClass : Placement -> String
placementToClass value =
    case value of
        Center ->
            "footer-center"
