-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Hero exposing (component, componentClasses, parts)

{-| Generated schema for the daisyUI `hero` component.

@docs component, componentClasses, parts

-}


{-| The main daisyUI class of the `hero` component.
-}
component : String
component =
    "hero"


{-| Every class in the `component` group of `hero`.
-}
componentClasses : List String
componentClasses =
    [ "hero"
    ]


{-| Every class in the `part` group of `hero`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    [ "hero-content"
    , "hero-overlay"
    ]
