-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Hover3d exposing (component, componentClasses, parts)

{-| Generated schema for the daisyUI `hover-3d` component.

@docs component, componentClasses, parts

-}


{-| The main daisyUI class of the `hover-3d` component.
-}
component : String
component =
    "hover-3d"


{-| Every class in the `component` group of `hover-3d`.
-}
componentClasses : List String
componentClasses =
    [ "hover-3d"
    ]


{-| Every class in the `part` group of `hover-3d`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []
