-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.HoverGallery exposing (component, componentClasses, parts)

{-| Generated schema for the daisyUI `hover-gallery` component.

@docs component, componentClasses, parts

-}


{-| The main daisyUI class of the `hover-gallery` component.
-}
component : String
component =
    "hover-gallery"


{-| Every class in the `component` group of `hover-gallery`.
-}
componentClasses : List String
componentClasses =
    [ "hover-gallery"
    ]


{-| Every class in the `part` group of `hover-gallery`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []
