-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Indicator exposing
    ( Placement(..)
    , allPlacements, component, componentClasses, parts, placementToClass
    )

{-| Generated schema for the daisyUI `indicator` component.

@docs Placement

@docs allPlacements, component, componentClasses, parts, placementToClass

-}


{-| The main daisyUI class of the `indicator` component.
-}
component : String
component =
    "indicator"


{-| Every class in the `component` group of `indicator`.
-}
componentClasses : List String
componentClasses =
    [ "indicator"
    ]


{-| Every class in the `part` group of `indicator`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    [ "indicator-item"
    ]


{-| The `placement` group of `indicator`. At most one value may be applied.
-}
type Placement
    = Start
    | Center
    | End
    | Top
    | Middle
    | Bottom


{-| Every [`Placement`](#Placement) value.
-}
allPlacements : List Placement
allPlacements =
    [ Start
    , Center
    , End
    , Top
    , Middle
    , Bottom
    ]


{-| The daisyUI class for a [`Placement`](#Placement).
-}
placementToClass : Placement -> String
placementToClass value =
    case value of
        Start ->
            "indicator-start"

        Center ->
            "indicator-center"

        End ->
            "indicator-end"

        Top ->
            "indicator-top"

        Middle ->
            "indicator-middle"

        Bottom ->
            "indicator-bottom"
