-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Input exposing
    ( Color(..), Size(..), Style(..)
    , allColors, allSizes, allStyles, colorToClass, component, componentClasses, parts, sizeToClass, styleToClass
    )

{-| Generated schema for the daisyUI `input` component.

@docs Color, Size, Style

@docs allColors, allSizes, allStyles, colorToClass, component, componentClasses, parts, sizeToClass, styleToClass

-}


{-| The main daisyUI class of the `input` component.
-}
component : String
component =
    "input"


{-| Every class in the `component` group of `input`.
-}
componentClasses : List String
componentClasses =
    [ "input"
    ]


{-| Every class in the `part` group of `input`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []


{-| The `color` group of `input`. At most one value may be applied.
-}
type Color
    = Neutral
    | Primary
    | Secondary
    | Accent
    | Info
    | Success
    | Warning
    | Error


{-| Every [`Color`](#Color) value.
-}
allColors : List Color
allColors =
    [ Neutral
    , Primary
    , Secondary
    , Accent
    , Info
    , Success
    , Warning
    , Error
    ]


{-| The daisyUI class for a [`Color`](#Color).
-}
colorToClass : Color -> String
colorToClass value =
    case value of
        Neutral ->
            "input-neutral"

        Primary ->
            "input-primary"

        Secondary ->
            "input-secondary"

        Accent ->
            "input-accent"

        Info ->
            "input-info"

        Success ->
            "input-success"

        Warning ->
            "input-warning"

        Error ->
            "input-error"


{-| The `style` group of `input`. At most one value may be applied.
-}
type Style
    = Ghost


{-| Every [`Style`](#Style) value.
-}
allStyles : List Style
allStyles =
    [ Ghost
    ]


{-| The daisyUI class for a [`Style`](#Style).
-}
styleToClass : Style -> String
styleToClass value =
    case value of
        Ghost ->
            "input-ghost"


{-| The `size` group of `input`. At most one value may be applied.
-}
type Size
    = Xs
    | Sm
    | Md
    | Lg
    | Xl


{-| Every [`Size`](#Size) value.
-}
allSizes : List Size
allSizes =
    [ Xs
    , Sm
    , Md
    , Lg
    , Xl
    ]


{-| The daisyUI class for a [`Size`](#Size).
-}
sizeToClass : Size -> String
sizeToClass value =
    case value of
        Xs ->
            "input-xs"

        Sm ->
            "input-sm"

        Md ->
            "input-md"

        Lg ->
            "input-lg"

        Xl ->
            "input-xl"
