-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Join exposing
    ( Direction(..)
    , allDirections, component, componentClasses, directionToClass, parts
    )

{-| Generated schema for the daisyUI `join` component.

@docs Direction

@docs allDirections, component, componentClasses, directionToClass, parts

-}


{-| The main daisyUI class of the `join` component.
-}
component : String
component =
    "join"


{-| Every class in the `component` group of `join`.
-}
componentClasses : List String
componentClasses =
    [ "join"
    , "join-item"
    ]


{-| Every class in the `part` group of `join`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []


{-| The `direction` group of `join`. At most one value may be applied.
-}
type Direction
    = Vertical
    | Horizontal


{-| Every [`Direction`](#Direction) value.
-}
allDirections : List Direction
allDirections =
    [ Vertical
    , Horizontal
    ]


{-| The daisyUI class for a [`Direction`](#Direction).
-}
directionToClass : Direction -> String
directionToClass value =
    case value of
        Vertical ->
            "join-vertical"

        Horizontal ->
            "join-horizontal"
