-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Kbd exposing
    ( Size(..)
    , allSizes, component, componentClasses, parts, sizeToClass
    )

{-| Generated schema for the daisyUI `kbd` component.

@docs Size

@docs allSizes, component, componentClasses, parts, sizeToClass

-}


{-| The main daisyUI class of the `kbd` component.
-}
component : String
component =
    "kbd"


{-| Every class in the `component` group of `kbd`.
-}
componentClasses : List String
componentClasses =
    [ "kbd"
    ]


{-| Every class in the `part` group of `kbd`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []


{-| The `size` group of `kbd`. At most one value may be applied.
-}
type Size
    = Xs
    | Sm
    | Md
    | Lg
    | Xl


{-| Every [`Size`](#Size) value.
-}
allSizes : List Size
allSizes =
    [ Xs
    , Sm
    , Md
    , Lg
    , Xl
    ]


{-| The daisyUI class for a [`Size`](#Size).
-}
sizeToClass : Size -> String
sizeToClass value =
    case value of
        Xs ->
            "kbd-xs"

        Sm ->
            "kbd-sm"

        Md ->
            "kbd-md"

        Lg ->
            "kbd-lg"

        Xl ->
            "kbd-xl"
