-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Label exposing (component, componentClasses, parts)

{-| Generated schema for the daisyUI `label` component.

@docs component, componentClasses, parts

-}


{-| The main daisyUI class of the `label` component.
-}
component : String
component =
    "label"


{-| Every class in the `component` group of `label`.
-}
componentClasses : List String
componentClasses =
    [ "label"
    , "floating-label"
    ]


{-| Every class in the `part` group of `label`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []
