-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Link exposing
    ( Color(..), Style(..)
    , allColors, allStyles, colorToClass, component, componentClasses, parts, styleToClass
    )

{-| Generated schema for the daisyUI `link` component.

@docs Color, Style

@docs allColors, allStyles, colorToClass, component, componentClasses, parts, styleToClass

-}


{-| The main daisyUI class of the `link` component.
-}
component : String
component =
    "link"


{-| Every class in the `component` group of `link`.
-}
componentClasses : List String
componentClasses =
    [ "link"
    ]


{-| Every class in the `part` group of `link`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []


{-| The `color` group of `link`. At most one value may be applied.
-}
type Color
    = Neutral
    | Primary
    | Secondary
    | Accent
    | Success
    | Info
    | Warning
    | Error


{-| Every [`Color`](#Color) value.
-}
allColors : List Color
allColors =
    [ Neutral
    , Primary
    , Secondary
    , Accent
    , Success
    , Info
    , Warning
    , Error
    ]


{-| The daisyUI class for a [`Color`](#Color).
-}
colorToClass : Color -> String
colorToClass value =
    case value of
        Neutral ->
            "link-neutral"

        Primary ->
            "link-primary"

        Secondary ->
            "link-secondary"

        Accent ->
            "link-accent"

        Success ->
            "link-success"

        Info ->
            "link-info"

        Warning ->
            "link-warning"

        Error ->
            "link-error"


{-| The `style` group of `link`. At most one value may be applied.
-}
type Style
    = Hover


{-| Every [`Style`](#Style) value.
-}
allStyles : List Style
allStyles =
    [ Hover
    ]


{-| The daisyUI class for a [`Style`](#Style).
-}
styleToClass : Style -> String
styleToClass value =
    case value of
        Hover ->
            "link-hover"
