-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.List exposing
    ( Modifier(..)
    , allModifiers, component, componentClasses, modifierToClass, parts
    )

{-| Generated schema for the daisyUI `list` component.

@docs Modifier

@docs allModifiers, component, componentClasses, modifierToClass, parts

-}


{-| The main daisyUI class of the `list` component.
-}
component : String
component =
    "list"


{-| Every class in the `component` group of `list`.
-}
componentClasses : List String
componentClasses =
    [ "list"
    , "list-row"
    ]


{-| Every class in the `part` group of `list`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []


{-| The `modifier` group of `list`. Any number of values may be applied.
-}
type Modifier
    = ColWrap
    | ColGrow


{-| Every [`Modifier`](#Modifier) value.
-}
allModifiers : List Modifier
allModifiers =
    [ ColWrap
    , ColGrow
    ]


{-| The daisyUI class for a [`Modifier`](#Modifier).
-}
modifierToClass : Modifier -> String
modifierToClass value =
    case value of
        ColWrap ->
            "list-col-wrap"

        ColGrow ->
            "list-col-grow"
