-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Loading exposing
    ( Size(..), Style(..)
    , allSizes, allStyles, component, componentClasses, parts, sizeToClass, styleToClass
    )

{-| Generated schema for the daisyUI `loading` component.

@docs Size, Style

@docs allSizes, allStyles, component, componentClasses, parts, sizeToClass, styleToClass

-}


{-| The main daisyUI class of the `loading` component.
-}
component : String
component =
    "loading"


{-| Every class in the `component` group of `loading`.
-}
componentClasses : List String
componentClasses =
    [ "loading"
    ]


{-| Every class in the `part` group of `loading`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []


{-| The `style` group of `loading`. At most one value may be applied.
-}
type Style
    = Spinner
    | Dots
    | Ring
    | Ball
    | Bars
    | Infinity


{-| Every [`Style`](#Style) value.
-}
allStyles : List Style
allStyles =
    [ Spinner
    , Dots
    , Ring
    , Ball
    , Bars
    , Infinity
    ]


{-| The daisyUI class for a [`Style`](#Style).
-}
styleToClass : Style -> String
styleToClass value =
    case value of
        Spinner ->
            "loading-spinner"

        Dots ->
            "loading-dots"

        Ring ->
            "loading-ring"

        Ball ->
            "loading-ball"

        Bars ->
            "loading-bars"

        Infinity ->
            "loading-infinity"


{-| The `size` group of `loading`. At most one value may be applied.
-}
type Size
    = Xs
    | Sm
    | Md
    | Lg
    | Xl


{-| Every [`Size`](#Size) value.
-}
allSizes : List Size
allSizes =
    [ Xs
    , Sm
    , Md
    , Lg
    , Xl
    ]


{-| The daisyUI class for a [`Size`](#Size).
-}
sizeToClass : Size -> String
sizeToClass value =
    case value of
        Xs ->
            "loading-xs"

        Sm ->
            "loading-sm"

        Md ->
            "loading-md"

        Lg ->
            "loading-lg"

        Xl ->
            "loading-xl"
