-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Mask exposing
    ( Modifier(..), Style(..)
    , allModifiers, allStyles, component, componentClasses, modifierToClass, parts, styleToClass
    )

{-| Generated schema for the daisyUI `mask` component.

@docs Modifier, Style

@docs allModifiers, allStyles, component, componentClasses, modifierToClass, parts, styleToClass

-}


{-| The main daisyUI class of the `mask` component.
-}
component : String
component =
    "mask"


{-| Every class in the `component` group of `mask`.
-}
componentClasses : List String
componentClasses =
    [ "mask"
    ]


{-| Every class in the `part` group of `mask`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []


{-| The `style` group of `mask`. At most one value may be applied.
-}
type Style
    = Squircle
    | Heart
    | Hexagon
    | Hexagon2
    | Decagon
    | Pentagon
    | Diamond
    | Circle
    | Star
    | Star2
    | Triangle
    | Triangle2
    | Triangle3
    | Triangle4


{-| Every [`Style`](#Style) value.
-}
allStyles : List Style
allStyles =
    [ Squircle
    , Heart
    , Hexagon
    , Hexagon2
    , Decagon
    , Pentagon
    , Diamond
    , Circle
    , Star
    , Star2
    , Triangle
    , Triangle2
    , Triangle3
    , Triangle4
    ]


{-| The daisyUI class for a [`Style`](#Style).
-}
styleToClass : Style -> String
styleToClass value =
    case value of
        Squircle ->
            "mask-squircle"

        Heart ->
            "mask-heart"

        Hexagon ->
            "mask-hexagon"

        Hexagon2 ->
            "mask-hexagon-2"

        Decagon ->
            "mask-decagon"

        Pentagon ->
            "mask-pentagon"

        Diamond ->
            "mask-diamond"

        Circle ->
            "mask-circle"

        Star ->
            "mask-star"

        Star2 ->
            "mask-star-2"

        Triangle ->
            "mask-triangle"

        Triangle2 ->
            "mask-triangle-2"

        Triangle3 ->
            "mask-triangle-3"

        Triangle4 ->
            "mask-triangle-4"


{-| The `modifier` group of `mask`. Any number of values may be applied.
-}
type Modifier
    = Half1
    | Half2


{-| Every [`Modifier`](#Modifier) value.
-}
allModifiers : List Modifier
allModifiers =
    [ Half1
    , Half2
    ]


{-| The daisyUI class for a [`Modifier`](#Modifier).
-}
modifierToClass : Modifier -> String
modifierToClass value =
    case value of
        Half1 ->
            "mask-half-1"

        Half2 ->
            "mask-half-2"
