-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Megamenu exposing
    ( Direction(..), Modifier(..), Size(..)
    , allDirections, allModifiers, allSizes, component, componentClasses, directionToClass, modifierToClass, parts, sizeToClass
    )

{-| Generated schema for the daisyUI `megamenu` component.

@docs Direction, Modifier, Size

@docs allDirections, allModifiers, allSizes, component, componentClasses, directionToClass, modifierToClass, parts, sizeToClass

-}


{-| The main daisyUI class of the `megamenu` component.
-}
component : String
component =
    "megamenu"


{-| Every class in the `component` group of `megamenu`.
-}
componentClasses : List String
componentClasses =
    [ "megamenu"
    ]


{-| Every class in the `part` group of `megamenu`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    [ "megamenu-active"
    ]


{-| The `size` group of `megamenu`. At most one value may be applied.
-}
type Size
    = Xs
    | Sm
    | Md
    | Lg
    | Xl


{-| Every [`Size`](#Size) value.
-}
allSizes : List Size
allSizes =
    [ Xs
    , Sm
    , Md
    , Lg
    , Xl
    ]


{-| The daisyUI class for a [`Size`](#Size).
-}
sizeToClass : Size -> String
sizeToClass value =
    case value of
        Xs ->
            "megamenu-xs"

        Sm ->
            "megamenu-sm"

        Md ->
            "megamenu-md"

        Lg ->
            "megamenu-lg"

        Xl ->
            "megamenu-xl"


{-| The `direction` group of `megamenu`. At most one value may be applied.
-}
type Direction
    = Vertical


{-| Every [`Direction`](#Direction) value.
-}
allDirections : List Direction
allDirections =
    [ Vertical
    ]


{-| The daisyUI class for a [`Direction`](#Direction).
-}
directionToClass : Direction -> String
directionToClass value =
    case value of
        Vertical ->
            "megamenu-vertical"


{-| The `modifier` group of `megamenu`. Any number of values may be applied.
-}
type Modifier
    = Wide
    | Full


{-| Every [`Modifier`](#Modifier) value.
-}
allModifiers : List Modifier
allModifiers =
    [ Wide
    , Full
    ]


{-| The daisyUI class for a [`Modifier`](#Modifier).
-}
modifierToClass : Modifier -> String
modifierToClass value =
    case value of
        Wide ->
            "megamenu-wide"

        Full ->
            "megamenu-full"
