-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Menu exposing
    ( Direction(..), Modifier(..), Size(..)
    , allDirections, allModifiers, allSizes, component, componentClasses, directionToClass, modifierToClass, parts, sizeToClass
    )

{-| Generated schema for the daisyUI `menu` component.

@docs Direction, Modifier, Size

@docs allDirections, allModifiers, allSizes, component, componentClasses, directionToClass, modifierToClass, parts, sizeToClass

-}


{-| The main daisyUI class of the `menu` component.
-}
component : String
component =
    "menu"


{-| Every class in the `component` group of `menu`.
-}
componentClasses : List String
componentClasses =
    [ "menu"
    ]


{-| Every class in the `part` group of `menu`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    [ "menu-title"
    , "menu-dropdown"
    , "menu-dropdown-toggle"
    ]


{-| The `size` group of `menu`. At most one value may be applied.
-}
type Size
    = Xs
    | Sm
    | Md
    | Lg
    | Xl


{-| Every [`Size`](#Size) value.
-}
allSizes : List Size
allSizes =
    [ Xs
    , Sm
    , Md
    , Lg
    , Xl
    ]


{-| The daisyUI class for a [`Size`](#Size).
-}
sizeToClass : Size -> String
sizeToClass value =
    case value of
        Xs ->
            "menu-xs"

        Sm ->
            "menu-sm"

        Md ->
            "menu-md"

        Lg ->
            "menu-lg"

        Xl ->
            "menu-xl"


{-| The `direction` group of `menu`. At most one value may be applied.
-}
type Direction
    = Vertical
    | Horizontal


{-| Every [`Direction`](#Direction) value.
-}
allDirections : List Direction
allDirections =
    [ Vertical
    , Horizontal
    ]


{-| The daisyUI class for a [`Direction`](#Direction).
-}
directionToClass : Direction -> String
directionToClass value =
    case value of
        Vertical ->
            "menu-vertical"

        Horizontal ->
            "menu-horizontal"


{-| The `modifier` group of `menu`. Any number of values may be applied.
-}
type Modifier
    = Disabled
    | Active
    | Focus
    | Show
    | Paged


{-| Every [`Modifier`](#Modifier) value.
-}
allModifiers : List Modifier
allModifiers =
    [ Disabled
    , Active
    , Focus
    , Show
    , Paged
    ]


{-| The daisyUI class for a [`Modifier`](#Modifier).
-}
modifierToClass : Modifier -> String
modifierToClass value =
    case value of
        Disabled ->
            "menu-disabled"

        Active ->
            "menu-active"

        Focus ->
            "menu-focus"

        Show ->
            "menu-dropdown-show"

        Paged ->
            "menu-paged"
