-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.MockupWindow exposing (component, componentClasses, parts)

{-| Generated schema for the daisyUI `mockup-window` component.

@docs component, componentClasses, parts

-}


{-| The main daisyUI class of the `mockup-window` component.
-}
component : String
component =
    "mockup-window"


{-| Every class in the `component` group of `mockup-window`.
-}
componentClasses : List String
componentClasses =
    [ "mockup-window"
    ]


{-| Every class in the `part` group of `mockup-window`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []
