-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.MockupPhone exposing (component, componentClasses, parts)

{-| Generated schema for the daisyUI `mockup-phone` component.

@docs component, componentClasses, parts

-}


{-| The main daisyUI class of the `mockup-phone` component.
-}
component : String
component =
    "mockup-phone"


{-| Every class in the `component` group of `mockup-phone`.
-}
componentClasses : List String
componentClasses =
    [ "mockup-phone"
    ]


{-| Every class in the `part` group of `mockup-phone`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    [ "mockup-phone-camera"
    , "mockup-phone-display"
    ]
