-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.MockupBrowser exposing (component, componentClasses, parts)

{-| Generated schema for the daisyUI `mockup-browser` component.

@docs component, componentClasses, parts

-}


{-| The main daisyUI class of the `mockup-browser` component.
-}
component : String
component =
    "mockup-browser"


{-| Every class in the `component` group of `mockup-browser`.
-}
componentClasses : List String
componentClasses =
    [ "mockup-browser"
    ]


{-| Every class in the `part` group of `mockup-browser`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    [ "mockup-browser-toolbar"
    ]
