-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.MockupCode exposing (component, componentClasses, parts)

{-| Generated schema for the daisyUI `mockup-code` component.

@docs component, componentClasses, parts

-}


{-| The main daisyUI class of the `mockup-code` component.
-}
component : String
component =
    "mockup-code"


{-| Every class in the `component` group of `mockup-code`.
-}
componentClasses : List String
componentClasses =
    [ "mockup-code"
    ]


{-| Every class in the `part` group of `mockup-code`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []
