-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Modal exposing
    ( Modifier(..), Placement(..)
    , allModifiers, allPlacements, component, componentClasses, modifierToClass, parts, placementToClass
    )

{-| Generated schema for the daisyUI `modal` component.

@docs Modifier, Placement

@docs allModifiers, allPlacements, component, componentClasses, modifierToClass, parts, placementToClass

-}


{-| The main daisyUI class of the `modal` component.
-}
component : String
component =
    "modal"


{-| Every class in the `component` group of `modal`.
-}
componentClasses : List String
componentClasses =
    [ "modal"
    ]


{-| Every class in the `part` group of `modal`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    [ "modal-box"
    , "modal-action"
    , "modal-backdrop"
    , "modal-toggle"
    ]


{-| The `placement` group of `modal`. At most one value may be applied.
-}
type Placement
    = Top
    | Middle
    | Bottom
    | Start
    | End


{-| Every [`Placement`](#Placement) value.
-}
allPlacements : List Placement
allPlacements =
    [ Top
    , Middle
    , Bottom
    , Start
    , End
    ]


{-| The daisyUI class for a [`Placement`](#Placement).
-}
placementToClass : Placement -> String
placementToClass value =
    case value of
        Top ->
            "modal-top"

        Middle ->
            "modal-middle"

        Bottom ->
            "modal-bottom"

        Start ->
            "modal-start"

        End ->
            "modal-end"


{-| The `modifier` group of `modal`. Any number of values may be applied.
-}
type Modifier
    = Open


{-| Every [`Modifier`](#Modifier) value.
-}
allModifiers : List Modifier
allModifiers =
    [ Open
    ]


{-| The daisyUI class for a [`Modifier`](#Modifier).
-}
modifierToClass : Modifier -> String
modifierToClass value =
    case value of
        Open ->
            "modal-open"
