-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Navbar exposing (component, componentClasses, parts)

{-| Generated schema for the daisyUI `navbar` component.

@docs component, componentClasses, parts

-}


{-| The main daisyUI class of the `navbar` component.
-}
component : String
component =
    "navbar"


{-| Every class in the `component` group of `navbar`.
-}
componentClasses : List String
componentClasses =
    [ "navbar"
    ]


{-| Every class in the `part` group of `navbar`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    [ "navbar-start"
    , "navbar-center"
    , "navbar-end"
    ]
