-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Otp exposing
    ( Color(..), Modifier(..), Size(..)
    , allColors, allModifiers, allSizes, colorToClass, component, componentClasses, modifierToClass, parts, sizeToClass
    )

{-| Generated schema for the daisyUI `otp` component.

@docs Color, Modifier, Size

@docs allColors, allModifiers, allSizes, colorToClass, component, componentClasses, modifierToClass, parts, sizeToClass

-}


{-| The main daisyUI class of the `otp` component.
-}
component : String
component =
    "otp"


{-| Every class in the `component` group of `otp`.
-}
componentClasses : List String
componentClasses =
    [ "otp"
    ]


{-| Every class in the `part` group of `otp`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []


{-| The `color` group of `otp`. At most one value may be applied.
-}
type Color
    = Neutral
    | Primary
    | Secondary
    | Accent
    | Success
    | Info
    | Warning
    | Error


{-| Every [`Color`](#Color) value.
-}
allColors : List Color
allColors =
    [ Neutral
    , Primary
    , Secondary
    , Accent
    , Success
    , Info
    , Warning
    , Error
    ]


{-| The daisyUI class for a [`Color`](#Color).
-}
colorToClass : Color -> String
colorToClass value =
    case value of
        Neutral ->
            "otp-neutral"

        Primary ->
            "otp-primary"

        Secondary ->
            "otp-secondary"

        Accent ->
            "otp-accent"

        Success ->
            "otp-success"

        Info ->
            "otp-info"

        Warning ->
            "otp-warning"

        Error ->
            "otp-error"


{-| The `size` group of `otp`. At most one value may be applied.
-}
type Size
    = Xs
    | Sm
    | Md
    | Lg
    | Xl


{-| Every [`Size`](#Size) value.
-}
allSizes : List Size
allSizes =
    [ Xs
    , Sm
    , Md
    , Lg
    , Xl
    ]


{-| The daisyUI class for a [`Size`](#Size).
-}
sizeToClass : Size -> String
sizeToClass value =
    case value of
        Xs ->
            "otp-xs"

        Sm ->
            "otp-sm"

        Md ->
            "otp-md"

        Lg ->
            "otp-lg"

        Xl ->
            "otp-xl"


{-| The `modifier` group of `otp`. Any number of values may be applied.
-}
type Modifier
    = Joined


{-| Every [`Modifier`](#Modifier) value.
-}
allModifiers : List Modifier
allModifiers =
    [ Joined
    ]


{-| The daisyUI class for a [`Modifier`](#Modifier).
-}
modifierToClass : Modifier -> String
modifierToClass value =
    case value of
        Joined ->
            "otp-joined"
