-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Progress exposing
    ( Color(..)
    , allColors, colorToClass, component, componentClasses, parts
    )

{-| Generated schema for the daisyUI `progress` component.

@docs Color

@docs allColors, colorToClass, component, componentClasses, parts

-}


{-| The main daisyUI class of the `progress` component.
-}
component : String
component =
    "progress"


{-| Every class in the `component` group of `progress`.
-}
componentClasses : List String
componentClasses =
    [ "progress"
    ]


{-| Every class in the `part` group of `progress`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []


{-| The `color` group of `progress`. At most one value may be applied.
-}
type Color
    = Neutral
    | Primary
    | Secondary
    | Accent
    | Info
    | Success
    | Warning
    | Error


{-| Every [`Color`](#Color) value.
-}
allColors : List Color
allColors =
    [ Neutral
    , Primary
    , Secondary
    , Accent
    , Info
    , Success
    , Warning
    , Error
    ]


{-| The daisyUI class for a [`Color`](#Color).
-}
colorToClass : Color -> String
colorToClass value =
    case value of
        Neutral ->
            "progress-neutral"

        Primary ->
            "progress-primary"

        Secondary ->
            "progress-secondary"

        Accent ->
            "progress-accent"

        Info ->
            "progress-info"

        Success ->
            "progress-success"

        Warning ->
            "progress-warning"

        Error ->
            "progress-error"
