-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Radio exposing
    ( Color(..), Size(..)
    , allColors, allSizes, colorToClass, component, componentClasses, parts, sizeToClass
    )

{-| Generated schema for the daisyUI `radio` component.

@docs Color, Size

@docs allColors, allSizes, colorToClass, component, componentClasses, parts, sizeToClass

-}


{-| The main daisyUI class of the `radio` component.
-}
component : String
component =
    "radio"


{-| Every class in the `component` group of `radio`.
-}
componentClasses : List String
componentClasses =
    [ "radio"
    ]


{-| Every class in the `part` group of `radio`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []


{-| The `color` group of `radio`. At most one value may be applied.
-}
type Color
    = Neutral
    | Primary
    | Secondary
    | Accent
    | Success
    | Warning
    | Info
    | Error


{-| Every [`Color`](#Color) value.
-}
allColors : List Color
allColors =
    [ Neutral
    , Primary
    , Secondary
    , Accent
    , Success
    , Warning
    , Info
    , Error
    ]


{-| The daisyUI class for a [`Color`](#Color).
-}
colorToClass : Color -> String
colorToClass value =
    case value of
        Neutral ->
            "radio-neutral"

        Primary ->
            "radio-primary"

        Secondary ->
            "radio-secondary"

        Accent ->
            "radio-accent"

        Success ->
            "radio-success"

        Warning ->
            "radio-warning"

        Info ->
            "radio-info"

        Error ->
            "radio-error"


{-| The `size` group of `radio`. At most one value may be applied.
-}
type Size
    = Xs
    | Sm
    | Md
    | Lg
    | Xl


{-| Every [`Size`](#Size) value.
-}
allSizes : List Size
allSizes =
    [ Xs
    , Sm
    , Md
    , Lg
    , Xl
    ]


{-| The daisyUI class for a [`Size`](#Size).
-}
sizeToClass : Size -> String
sizeToClass value =
    case value of
        Xs ->
            "radio-xs"

        Sm ->
            "radio-sm"

        Md ->
            "radio-md"

        Lg ->
            "radio-lg"

        Xl ->
            "radio-xl"
