-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.RadialProgress exposing (component, componentClasses, parts)

{-| Generated schema for the daisyUI `radial-progress` component.

@docs component, componentClasses, parts

-}


{-| The main daisyUI class of the `radial-progress` component.
-}
component : String
component =
    "radial-progress"


{-| Every class in the `component` group of `radial-progress`.
-}
componentClasses : List String
componentClasses =
    [ "radial-progress"
    ]


{-| Every class in the `part` group of `radial-progress`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []
