-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Range exposing
    ( Color(..), Direction(..), Size(..)
    , allColors, allDirections, allSizes, colorToClass, component, componentClasses, directionToClass, parts, sizeToClass
    )

{-| Generated schema for the daisyUI `range` component.

@docs Color, Direction, Size

@docs allColors, allDirections, allSizes, colorToClass, component, componentClasses, directionToClass, parts, sizeToClass

-}


{-| The main daisyUI class of the `range` component.
-}
component : String
component =
    "range"


{-| Every class in the `component` group of `range`.
-}
componentClasses : List String
componentClasses =
    [ "range"
    ]


{-| Every class in the `part` group of `range`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []


{-| The `color` group of `range`. At most one value may be applied.
-}
type Color
    = Neutral
    | Primary
    | Secondary
    | Accent
    | Success
    | Warning
    | Info
    | Error


{-| Every [`Color`](#Color) value.
-}
allColors : List Color
allColors =
    [ Neutral
    , Primary
    , Secondary
    , Accent
    , Success
    , Warning
    , Info
    , Error
    ]


{-| The daisyUI class for a [`Color`](#Color).
-}
colorToClass : Color -> String
colorToClass value =
    case value of
        Neutral ->
            "range-neutral"

        Primary ->
            "range-primary"

        Secondary ->
            "range-secondary"

        Accent ->
            "range-accent"

        Success ->
            "range-success"

        Warning ->
            "range-warning"

        Info ->
            "range-info"

        Error ->
            "range-error"


{-| The `size` group of `range`. At most one value may be applied.
-}
type Size
    = Xs
    | Sm
    | Md
    | Lg
    | Xl


{-| Every [`Size`](#Size) value.
-}
allSizes : List Size
allSizes =
    [ Xs
    , Sm
    , Md
    , Lg
    , Xl
    ]


{-| The daisyUI class for a [`Size`](#Size).
-}
sizeToClass : Size -> String
sizeToClass value =
    case value of
        Xs ->
            "range-xs"

        Sm ->
            "range-sm"

        Md ->
            "range-md"

        Lg ->
            "range-lg"

        Xl ->
            "range-xl"


{-| The `direction` group of `range`. At most one value may be applied.
-}
type Direction
    = Vertical


{-| Every [`Direction`](#Direction) value.
-}
allDirections : List Direction
allDirections =
    [ Vertical
    ]


{-| The daisyUI class for a [`Direction`](#Direction).
-}
directionToClass : Direction -> String
directionToClass value =
    case value of
        Vertical ->
            "range-vertical"
