-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Rating exposing
    ( Modifier(..), Size(..)
    , allModifiers, allSizes, component, componentClasses, modifierToClass, parts, sizeToClass
    )

{-| Generated schema for the daisyUI `rating` component.

@docs Modifier, Size

@docs allModifiers, allSizes, component, componentClasses, modifierToClass, parts, sizeToClass

-}


{-| The main daisyUI class of the `rating` component.
-}
component : String
component =
    "rating"


{-| Every class in the `component` group of `rating`.
-}
componentClasses : List String
componentClasses =
    [ "rating"
    ]


{-| Every class in the `part` group of `rating`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []


{-| The `size` group of `rating`. At most one value may be applied.
-}
type Size
    = Xs
    | Sm
    | Md
    | Lg
    | Xl


{-| Every [`Size`](#Size) value.
-}
allSizes : List Size
allSizes =
    [ Xs
    , Sm
    , Md
    , Lg
    , Xl
    ]


{-| The daisyUI class for a [`Size`](#Size).
-}
sizeToClass : Size -> String
sizeToClass value =
    case value of
        Xs ->
            "rating-xs"

        Sm ->
            "rating-sm"

        Md ->
            "rating-md"

        Lg ->
            "rating-lg"

        Xl ->
            "rating-xl"


{-| The `modifier` group of `rating`. Any number of values may be applied.
-}
type Modifier
    = Half
    | Hidden


{-| Every [`Modifier`](#Modifier) value.
-}
allModifiers : List Modifier
allModifiers =
    [ Half
    , Hidden
    ]


{-| The daisyUI class for a [`Modifier`](#Modifier).
-}
modifierToClass : Modifier -> String
modifierToClass value =
    case value of
        Half ->
            "rating-half"

        Hidden ->
            "rating-hidden"
