-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Skeleton exposing
    ( Modifier(..)
    , allModifiers, component, componentClasses, modifierToClass, parts
    )

{-| Generated schema for the daisyUI `skeleton` component.

@docs Modifier

@docs allModifiers, component, componentClasses, modifierToClass, parts

-}


{-| The main daisyUI class of the `skeleton` component.
-}
component : String
component =
    "skeleton"


{-| Every class in the `component` group of `skeleton`.
-}
componentClasses : List String
componentClasses =
    [ "skeleton"
    ]


{-| Every class in the `part` group of `skeleton`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []


{-| The `modifier` group of `skeleton`. Any number of values may be applied.
-}
type Modifier
    = Text


{-| Every [`Modifier`](#Modifier) value.
-}
allModifiers : List Modifier
allModifiers =
    [ Text
    ]


{-| The daisyUI class for a [`Modifier`](#Modifier).
-}
modifierToClass : Modifier -> String
modifierToClass value =
    case value of
        Text ->
            "skeleton-text"
