-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Stack exposing
    ( Modifier(..)
    , allModifiers, component, componentClasses, modifierToClass, parts
    )

{-| Generated schema for the daisyUI `stack` component.

@docs Modifier

@docs allModifiers, component, componentClasses, modifierToClass, parts

-}


{-| The main daisyUI class of the `stack` component.
-}
component : String
component =
    "stack"


{-| Every class in the `component` group of `stack`.
-}
componentClasses : List String
componentClasses =
    [ "stack"
    ]


{-| Every class in the `part` group of `stack`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []


{-| The `modifier` group of `stack`. Any number of values may be applied.
-}
type Modifier
    = Top
    | Bottom
    | Start
    | End


{-| Every [`Modifier`](#Modifier) value.
-}
allModifiers : List Modifier
allModifiers =
    [ Top
    , Bottom
    , Start
    , End
    ]


{-| The daisyUI class for a [`Modifier`](#Modifier).
-}
modifierToClass : Modifier -> String
modifierToClass value =
    case value of
        Top ->
            "stack-top"

        Bottom ->
            "stack-bottom"

        Start ->
            "stack-start"

        End ->
            "stack-end"
