-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Stat exposing
    ( Direction(..)
    , allDirections, component, componentClasses, directionToClass, parts
    )

{-| Generated schema for the daisyUI `stat` component.

@docs Direction

@docs allDirections, component, componentClasses, directionToClass, parts

-}


{-| The main daisyUI class of the `stat` component.
-}
component : String
component =
    "stats"


{-| Every class in the `component` group of `stat`.
-}
componentClasses : List String
componentClasses =
    [ "stats"
    ]


{-| Every class in the `part` group of `stat`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    [ "stat"
    , "stat-title"
    , "stat-value"
    , "stat-desc"
    , "stat-figure"
    , "stat-actions"
    ]


{-| The `direction` group of `stat`. At most one value may be applied.
-}
type Direction
    = Horizontal
    | Vertical


{-| Every [`Direction`](#Direction) value.
-}
allDirections : List Direction
allDirections =
    [ Horizontal
    , Vertical
    ]


{-| The daisyUI class for a [`Direction`](#Direction).
-}
directionToClass : Direction -> String
directionToClass value =
    case value of
        Horizontal ->
            "stats-horizontal"

        Vertical ->
            "stats-vertical"
