-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Status exposing
    ( Color(..), Size(..)
    , allColors, allSizes, colorToClass, component, componentClasses, parts, sizeToClass
    )

{-| Generated schema for the daisyUI `status` component.

@docs Color, Size

@docs allColors, allSizes, colorToClass, component, componentClasses, parts, sizeToClass

-}


{-| The main daisyUI class of the `status` component.
-}
component : String
component =
    "status"


{-| Every class in the `component` group of `status`.
-}
componentClasses : List String
componentClasses =
    [ "status"
    ]


{-| Every class in the `part` group of `status`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []


{-| The `color` group of `status`. At most one value may be applied.
-}
type Color
    = Neutral
    | Primary
    | Secondary
    | Accent
    | Info
    | Success
    | Warning
    | Error


{-| Every [`Color`](#Color) value.
-}
allColors : List Color
allColors =
    [ Neutral
    , Primary
    , Secondary
    , Accent
    , Info
    , Success
    , Warning
    , Error
    ]


{-| The daisyUI class for a [`Color`](#Color).
-}
colorToClass : Color -> String
colorToClass value =
    case value of
        Neutral ->
            "status-neutral"

        Primary ->
            "status-primary"

        Secondary ->
            "status-secondary"

        Accent ->
            "status-accent"

        Info ->
            "status-info"

        Success ->
            "status-success"

        Warning ->
            "status-warning"

        Error ->
            "status-error"


{-| The `size` group of `status`. At most one value may be applied.
-}
type Size
    = Xs
    | Sm
    | Md
    | Lg
    | Xl


{-| Every [`Size`](#Size) value.
-}
allSizes : List Size
allSizes =
    [ Xs
    , Sm
    , Md
    , Lg
    , Xl
    ]


{-| The daisyUI class for a [`Size`](#Size).
-}
sizeToClass : Size -> String
sizeToClass value =
    case value of
        Xs ->
            "status-xs"

        Sm ->
            "status-sm"

        Md ->
            "status-md"

        Lg ->
            "status-lg"

        Xl ->
            "status-xl"
