-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Steps exposing
    ( Color(..), Direction(..)
    , allColors, allDirections, colorToClass, component, componentClasses, directionToClass, parts
    )

{-| Generated schema for the daisyUI `steps` component.

@docs Color, Direction

@docs allColors, allDirections, colorToClass, component, componentClasses, directionToClass, parts

-}


{-| The main daisyUI class of the `steps` component.
-}
component : String
component =
    "steps"


{-| Every class in the `component` group of `steps`.
-}
componentClasses : List String
componentClasses =
    [ "steps"
    ]


{-| Every class in the `part` group of `steps`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    [ "step"
    , "step-icon"
    ]


{-| The `color` group of `steps`. At most one value may be applied.
-}
type Color
    = Neutral
    | Primary
    | Secondary
    | Accent
    | Info
    | Success
    | Warning
    | Error


{-| Every [`Color`](#Color) value.
-}
allColors : List Color
allColors =
    [ Neutral
    , Primary
    , Secondary
    , Accent
    , Info
    , Success
    , Warning
    , Error
    ]


{-| The daisyUI class for a [`Color`](#Color).
-}
colorToClass : Color -> String
colorToClass value =
    case value of
        Neutral ->
            "step-neutral"

        Primary ->
            "step-primary"

        Secondary ->
            "step-secondary"

        Accent ->
            "step-accent"

        Info ->
            "step-info"

        Success ->
            "step-success"

        Warning ->
            "step-warning"

        Error ->
            "step-error"


{-| The `direction` group of `steps`. At most one value may be applied.
-}
type Direction
    = Vertical
    | Horizontal


{-| Every [`Direction`](#Direction) value.
-}
allDirections : List Direction
allDirections =
    [ Vertical
    , Horizontal
    ]


{-| The daisyUI class for a [`Direction`](#Direction).
-}
directionToClass : Direction -> String
directionToClass value =
    case value of
        Vertical ->
            "steps-vertical"

        Horizontal ->
            "steps-horizontal"
