-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Swap exposing
    ( Modifier(..), Style(..)
    , allModifiers, allStyles, component, componentClasses, modifierToClass, parts, styleToClass
    )

{-| Generated schema for the daisyUI `swap` component.

@docs Modifier, Style

@docs allModifiers, allStyles, component, componentClasses, modifierToClass, parts, styleToClass

-}


{-| The main daisyUI class of the `swap` component.
-}
component : String
component =
    "swap"


{-| Every class in the `component` group of `swap`.
-}
componentClasses : List String
componentClasses =
    [ "swap"
    ]


{-| Every class in the `part` group of `swap`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    [ "swap-on"
    , "swap-off"
    , "swap-indeterminate"
    ]


{-| The `style` group of `swap`. At most one value may be applied.
-}
type Style
    = Rotate
    | Flip


{-| Every [`Style`](#Style) value.
-}
allStyles : List Style
allStyles =
    [ Rotate
    , Flip
    ]


{-| The daisyUI class for a [`Style`](#Style).
-}
styleToClass : Style -> String
styleToClass value =
    case value of
        Rotate ->
            "swap-rotate"

        Flip ->
            "swap-flip"


{-| The `modifier` group of `swap`. Any number of values may be applied.
-}
type Modifier
    = Active


{-| Every [`Modifier`](#Modifier) value.
-}
allModifiers : List Modifier
allModifiers =
    [ Active
    ]


{-| The daisyUI class for a [`Modifier`](#Modifier).
-}
modifierToClass : Modifier -> String
modifierToClass value =
    case value of
        Active ->
            "swap-active"
