-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Tab exposing
    ( Modifier(..), Placement(..), Size(..), Style(..)
    , allModifiers, allPlacements, allSizes, allStyles, component, componentClasses, modifierToClass, parts, placementToClass, sizeToClass, styleToClass
    )

{-| Generated schema for the daisyUI `tab` component.

@docs Modifier, Placement, Size, Style

@docs allModifiers, allPlacements, allSizes, allStyles, component, componentClasses, modifierToClass, parts, placementToClass, sizeToClass, styleToClass

-}


{-| The main daisyUI class of the `tab` component.
-}
component : String
component =
    "tabs"


{-| Every class in the `component` group of `tab`.
-}
componentClasses : List String
componentClasses =
    [ "tabs"
    ]


{-| Every class in the `part` group of `tab`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    [ "tab"
    , "tab-content"
    ]


{-| The `style` group of `tab`. At most one value may be applied.
-}
type Style
    = Box
    | Border
    | Lift


{-| Every [`Style`](#Style) value.
-}
allStyles : List Style
allStyles =
    [ Box
    , Border
    , Lift
    ]


{-| The daisyUI class for a [`Style`](#Style).
-}
styleToClass : Style -> String
styleToClass value =
    case value of
        Box ->
            "tabs-box"

        Border ->
            "tabs-border"

        Lift ->
            "tabs-lift"


{-| The `size` group of `tab`. At most one value may be applied.
-}
type Size
    = Xs
    | Sm
    | Md
    | Lg
    | Xl


{-| Every [`Size`](#Size) value.
-}
allSizes : List Size
allSizes =
    [ Xs
    , Sm
    , Md
    , Lg
    , Xl
    ]


{-| The daisyUI class for a [`Size`](#Size).
-}
sizeToClass : Size -> String
sizeToClass value =
    case value of
        Xs ->
            "tabs-xs"

        Sm ->
            "tabs-sm"

        Md ->
            "tabs-md"

        Lg ->
            "tabs-lg"

        Xl ->
            "tabs-xl"


{-| The `placement` group of `tab`. At most one value may be applied.
-}
type Placement
    = Top
    | Bottom


{-| Every [`Placement`](#Placement) value.
-}
allPlacements : List Placement
allPlacements =
    [ Top
    , Bottom
    ]


{-| The daisyUI class for a [`Placement`](#Placement).
-}
placementToClass : Placement -> String
placementToClass value =
    case value of
        Top ->
            "tabs-top"

        Bottom ->
            "tabs-bottom"


{-| The `modifier` group of `tab`. Any number of values may be applied.
-}
type Modifier
    = Active
    | Disabled


{-| Every [`Modifier`](#Modifier) value.
-}
allModifiers : List Modifier
allModifiers =
    [ Active
    , Disabled
    ]


{-| The daisyUI class for a [`Modifier`](#Modifier).
-}
modifierToClass : Modifier -> String
modifierToClass value =
    case value of
        Active ->
            "tab-active"

        Disabled ->
            "tab-disabled"
