-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Table exposing
    ( Modifier(..), Size(..)
    , allModifiers, allSizes, component, componentClasses, modifierToClass, parts, sizeToClass
    )

{-| Generated schema for the daisyUI `table` component.

@docs Modifier, Size

@docs allModifiers, allSizes, component, componentClasses, modifierToClass, parts, sizeToClass

-}


{-| The main daisyUI class of the `table` component.
-}
component : String
component =
    "table"


{-| Every class in the `component` group of `table`.
-}
componentClasses : List String
componentClasses =
    [ "table"
    ]


{-| Every class in the `part` group of `table`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []


{-| The `size` group of `table`. At most one value may be applied.
-}
type Size
    = Xs
    | Sm
    | Md
    | Lg
    | Xl


{-| Every [`Size`](#Size) value.
-}
allSizes : List Size
allSizes =
    [ Xs
    , Sm
    , Md
    , Lg
    , Xl
    ]


{-| The daisyUI class for a [`Size`](#Size).
-}
sizeToClass : Size -> String
sizeToClass value =
    case value of
        Xs ->
            "table-xs"

        Sm ->
            "table-sm"

        Md ->
            "table-md"

        Lg ->
            "table-lg"

        Xl ->
            "table-xl"


{-| The `modifier` group of `table`. Any number of values may be applied.
-}
type Modifier
    = Zebra
    | PinRows
    | PinCols


{-| Every [`Modifier`](#Modifier) value.
-}
allModifiers : List Modifier
allModifiers =
    [ Zebra
    , PinRows
    , PinCols
    ]


{-| The daisyUI class for a [`Modifier`](#Modifier).
-}
modifierToClass : Modifier -> String
modifierToClass value =
    case value of
        Zebra ->
            "table-zebra"

        PinRows ->
            "table-pin-rows"

        PinCols ->
            "table-pin-cols"
