-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.TextRotate exposing (component, componentClasses, parts)

{-| Generated schema for the daisyUI `text-rotate` component.

@docs component, componentClasses, parts

-}


{-| The main daisyUI class of the `text-rotate` component.
-}
component : String
component =
    "text-rotate"


{-| Every class in the `component` group of `text-rotate`.
-}
componentClasses : List String
componentClasses =
    [ "text-rotate"
    ]


{-| Every class in the `part` group of `text-rotate`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []
