-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.ThemeController exposing (component, componentClasses, parts)

{-| Generated schema for the daisyUI `theme-controller` component.

@docs component, componentClasses, parts

-}


{-| The main daisyUI class of the `theme-controller` component.
-}
component : String
component =
    "theme-controller"


{-| Every class in the `component` group of `theme-controller`.
-}
componentClasses : List String
componentClasses =
    [ "theme-controller"
    ]


{-| Every class in the `part` group of `theme-controller`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []
