-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Timeline exposing
    ( Direction(..), Modifier(..)
    , allDirections, allModifiers, component, componentClasses, directionToClass, modifierToClass, parts
    )

{-| Generated schema for the daisyUI `timeline` component.

@docs Direction, Modifier

@docs allDirections, allModifiers, component, componentClasses, directionToClass, modifierToClass, parts

-}


{-| The main daisyUI class of the `timeline` component.
-}
component : String
component =
    "timeline"


{-| Every class in the `component` group of `timeline`.
-}
componentClasses : List String
componentClasses =
    [ "timeline"
    ]


{-| Every class in the `part` group of `timeline`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    [ "timeline-start"
    , "timeline-middle"
    , "timeline-end"
    ]


{-| The `direction` group of `timeline`. At most one value may be applied.
-}
type Direction
    = Horizontal
    | Vertical


{-| Every [`Direction`](#Direction) value.
-}
allDirections : List Direction
allDirections =
    [ Horizontal
    , Vertical
    ]


{-| The daisyUI class for a [`Direction`](#Direction).
-}
directionToClass : Direction -> String
directionToClass value =
    case value of
        Horizontal ->
            "timeline-horizontal"

        Vertical ->
            "timeline-vertical"


{-| The `modifier` group of `timeline`. Any number of values may be applied.
-}
type Modifier
    = SnapIcon
    | Box
    | Compact


{-| Every [`Modifier`](#Modifier) value.
-}
allModifiers : List Modifier
allModifiers =
    [ SnapIcon
    , Box
    , Compact
    ]


{-| The daisyUI class for a [`Modifier`](#Modifier).
-}
modifierToClass : Modifier -> String
modifierToClass value =
    case value of
        SnapIcon ->
            "timeline-snap-icon"

        Box ->
            "timeline-box"

        Compact ->
            "timeline-compact"
