-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Toast exposing
    ( Placement(..)
    , allPlacements, component, componentClasses, parts, placementToClass
    )

{-| Generated schema for the daisyUI `toast` component.

@docs Placement

@docs allPlacements, component, componentClasses, parts, placementToClass

-}


{-| The main daisyUI class of the `toast` component.
-}
component : String
component =
    "toast"


{-| Every class in the `component` group of `toast`.
-}
componentClasses : List String
componentClasses =
    [ "toast"
    ]


{-| Every class in the `part` group of `toast`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []


{-| The `placement` group of `toast`. At most one value may be applied.
-}
type Placement
    = Start
    | Center
    | End
    | Top
    | Middle
    | Bottom


{-| Every [`Placement`](#Placement) value.
-}
allPlacements : List Placement
allPlacements =
    [ Start
    , Center
    , End
    , Top
    , Middle
    , Bottom
    ]


{-| The daisyUI class for a [`Placement`](#Placement).
-}
placementToClass : Placement -> String
placementToClass value =
    case value of
        Start ->
            "toast-start"

        Center ->
            "toast-center"

        End ->
            "toast-end"

        Top ->
            "toast-top"

        Middle ->
            "toast-middle"

        Bottom ->
            "toast-bottom"
