-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Toggle exposing
    ( Color(..), Size(..)
    , allColors, allSizes, colorToClass, component, componentClasses, parts, sizeToClass
    )

{-| Generated schema for the daisyUI `toggle` component.

@docs Color, Size

@docs allColors, allSizes, colorToClass, component, componentClasses, parts, sizeToClass

-}


{-| The main daisyUI class of the `toggle` component.
-}
component : String
component =
    "toggle"


{-| Every class in the `component` group of `toggle`.
-}
componentClasses : List String
componentClasses =
    [ "toggle"
    ]


{-| Every class in the `part` group of `toggle`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    []


{-| The `color` group of `toggle`. At most one value may be applied.
-}
type Color
    = Primary
    | Secondary
    | Accent
    | Neutral
    | Success
    | Warning
    | Info
    | Error


{-| Every [`Color`](#Color) value.
-}
allColors : List Color
allColors =
    [ Primary
    , Secondary
    , Accent
    , Neutral
    , Success
    , Warning
    , Info
    , Error
    ]


{-| The daisyUI class for a [`Color`](#Color).
-}
colorToClass : Color -> String
colorToClass value =
    case value of
        Primary ->
            "toggle-primary"

        Secondary ->
            "toggle-secondary"

        Accent ->
            "toggle-accent"

        Neutral ->
            "toggle-neutral"

        Success ->
            "toggle-success"

        Warning ->
            "toggle-warning"

        Info ->
            "toggle-info"

        Error ->
            "toggle-error"


{-| The `size` group of `toggle`. At most one value may be applied.
-}
type Size
    = Xs
    | Sm
    | Md
    | Lg
    | Xl


{-| Every [`Size`](#Size) value.
-}
allSizes : List Size
allSizes =
    [ Xs
    , Sm
    , Md
    , Lg
    , Xl
    ]


{-| The daisyUI class for a [`Size`](#Size).
-}
sizeToClass : Size -> String
sizeToClass value =
    case value of
        Xs ->
            "toggle-xs"

        Sm ->
            "toggle-sm"

        Md ->
            "toggle-md"

        Lg ->
            "toggle-lg"

        Xl ->
            "toggle-xl"
