-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Tooltip exposing
    ( Color(..), Modifier(..), Placement(..)
    , allColors, allModifiers, allPlacements, colorToClass, component, componentClasses, modifierToClass, parts, placementToClass
    )

{-| Generated schema for the daisyUI `tooltip` component.

@docs Color, Modifier, Placement

@docs allColors, allModifiers, allPlacements, colorToClass, component, componentClasses, modifierToClass, parts, placementToClass

-}


{-| The main daisyUI class of the `tooltip` component.
-}
component : String
component =
    "tooltip"


{-| Every class in the `component` group of `tooltip`.
-}
componentClasses : List String
componentClasses =
    [ "tooltip"
    ]


{-| Every class in the `part` group of `tooltip`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    [ "tooltip-content"
    ]


{-| The `color` group of `tooltip`. At most one value may be applied.
-}
type Color
    = Primary
    | Secondary
    | Accent
    | Info
    | Success
    | Warning
    | Error


{-| Every [`Color`](#Color) value.
-}
allColors : List Color
allColors =
    [ Primary
    , Secondary
    , Accent
    , Info
    , Success
    , Warning
    , Error
    ]


{-| The daisyUI class for a [`Color`](#Color).
-}
colorToClass : Color -> String
colorToClass value =
    case value of
        Primary ->
            "tooltip-primary"

        Secondary ->
            "tooltip-secondary"

        Accent ->
            "tooltip-accent"

        Info ->
            "tooltip-info"

        Success ->
            "tooltip-success"

        Warning ->
            "tooltip-warning"

        Error ->
            "tooltip-error"


{-| The `placement` group of `tooltip`. At most one value may be applied.
-}
type Placement
    = Top
    | Bottom
    | Left
    | Right
    | Start
    | Center
    | End


{-| Every [`Placement`](#Placement) value.
-}
allPlacements : List Placement
allPlacements =
    [ Top
    , Bottom
    , Left
    , Right
    , Start
    , Center
    , End
    ]


{-| The daisyUI class for a [`Placement`](#Placement).
-}
placementToClass : Placement -> String
placementToClass value =
    case value of
        Top ->
            "tooltip-top"

        Bottom ->
            "tooltip-bottom"

        Left ->
            "tooltip-left"

        Right ->
            "tooltip-right"

        Start ->
            "tooltip-start"

        Center ->
            "tooltip-center"

        End ->
            "tooltip-end"


{-| The `modifier` group of `tooltip`. Any number of values may be applied.
-}
type Modifier
    = Open


{-| Every [`Modifier`](#Modifier) value.
-}
allModifiers : List Modifier
allModifiers =
    [ Open
    ]


{-| The daisyUI class for a [`Modifier`](#Modifier).
-}
modifierToClass : Modifier -> String
modifierToClass value =
    case value of
        Open ->
            "tooltip-open"
