-- GENERATED by tools/gen-schema.js. Do not edit.


module Daisy.Schema.Validator exposing (component, componentClasses, parts)

{-| Generated schema for the daisyUI `validator` component.

@docs component, componentClasses, parts

-}


{-| The main daisyUI class of the `validator` component.
-}
component : String
component =
    "validator"


{-| Every class in the `component` group of `validator`.
-}
componentClasses : List String
componentClasses =
    [ "validator"
    ]


{-| Every class in the `part` group of `validator`. A part is only valid
inside an element carrying `component`.
-}
parts : List String
parts =
    [ "validator-hint"
    ]
